name: ioc_container
description: The Container Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  dsr_container: ^0.1.0
  platform_contracts: ^0.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  mockito: ^5.4.0
  test: ^1.24.0
  platform_config: ^0.1.0
