name: platform_support
description: Core support utilities and helper functions for the framework
version: 1.0.0
homepage: https://github.com/yourusername/platform

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  meta: ^1.9.0
  path: ^1.8.0
  crypto: ^3.0.0
  uuid: ^4.0.0
  intl: ^0.18.0
  glob: ^2.1.0
  yaml: ^3.1.2
  pub_semver: ^2.1.4
  platform_collections: ^1.0.0
  platform_conditionable: ^1.0.0
  platform_contracts: ^1.0.0
  platform_macroable: ^1.0.0
  platform_mirrors: ^1.0.0
  
  

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

topics:
  - framework
  - utilities
  - support
