name: illuminate_support
description: The support package for the protevus platform
version: 0.5.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  collection: ^1.17.0
  encrypt: ^5.0.3
  meta: ^1.9.0
  path: ^1.8.0
  crypto: ^3.0.0
  uuid: ^3.0.6
  intl: ^0.17.0
  glob: ^2.1.0
  yaml: ^3.1.2
  pub_semver: ^2.1.4
  illuminate_collections: ^0.5.1
  illuminate_conditionable: ^0.5.1
  illuminate_container: ^0.5.1
  illuminate_contracts: ^0.5.1
  illuminate_foundation: ^0.5.1
  illuminate_macroable: ^0.5.1
  illuminate_mirrors: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
