name: illuminate_support
description: The support package for the protevus platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  encrypt: ^5.0.3
  bcrypt: ^1.1.3
  illuminate_contracts: ^0.0.1
  illuminate_foundation: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
