name: dsr_link
description: A PSR-13 compatible link interface for Dart. Provides standardized interfaces for working with web links, including link objects and link providers with support for HTTP Link headers.
version: 0.0.1
homepage: https://dart-fig.org

environment:
  sdk: ^3.4.2

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
