name: illuminate_encryption
description: The Encryption Package for the Protevus Platform
version: 0.5.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  encrypt: ^5.0.3
  illuminate_contracts: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
