name: Package
class_comment: '# * Basic package that adds a version to asset URLs.

  # *

  # * @author Kris Wallsmith <kris@symfony.com>

  # * @author Fabien Potencier <fabien@symfony.com>'
dependencies:
- name: ContextInterface
  type: class
  source: Symfony\Component\Asset\Context\ContextInterface
- name: NullContext
  type: class
  source: Symfony\Component\Asset\Context\NullContext
- name: VersionStrategyInterface
  type: class
  source: Symfony\Component\Asset\VersionStrategy\VersionStrategyInterface
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: versionStrategy
  - name: context
    default: 'null'
  comment: null
- name: getVersion
  visibility: public
  parameters:
  - name: path
  comment: null
- name: getUrl
  visibility: public
  parameters:
  - name: path
  comment: null
- name: getContext
  visibility: protected
  parameters: []
  comment: null
- name: getVersionStrategy
  visibility: protected
  parameters: []
  comment: null
- name: isAbsoluteUrl
  visibility: protected
  parameters:
  - name: url
  comment: null
traits:
- Symfony\Component\Asset\Context\ContextInterface
- Symfony\Component\Asset\Context\NullContext
- Symfony\Component\Asset\VersionStrategy\VersionStrategyInterface
interfaces:
- PackageInterface
