name: platform_route
version: 9.0.0
description: A powerful, isomorphic routing library for Dart. It is mainly used in the Protevus Platform, but can be used in Flutter and on the Web.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/route
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  belatuk_combinator: ^5.2.0
  string_scanner: ^1.4.0
  path: ^1.9.1
dev_dependencies:
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  http: ^1.2.2
  test: ^1.25.8
  lints: ^4.0.0
