name: PacksPhpRedisValues
class_comment: null
dependencies:
- name: Redis
  type: class
  source: Redis
- name: RuntimeException
  type: class
  source: RuntimeException
- name: UnexpectedValueException
  type: class
  source: UnexpectedValueException
properties:
- name: supportsPacking
  visibility: protected
  comment: '# * Indicates if Redis supports packing.

    # *

    # * @var bool|null'
- name: supportsLzf
  visibility: protected
  comment: '# * Indicates if Redis supports LZF compression.

    # *

    # * @var bool|null'
- name: supportsZstd
  visibility: protected
  comment: '# * Indicates if Redis supports Zstd compression.

    # *

    # * @var bool|null'
methods:
- name: pack
  visibility: public
  parameters:
  - name: values
  comment: "# * Indicates if Redis supports packing.\n# *\n# * @var bool|null\n# */\n\
    # protected $supportsPacking;\n# \n# /**\n# * Indicates if Redis supports LZF\
    \ compression.\n# *\n# * @var bool|null\n# */\n# protected $supportsLzf;\n# \n\
    # /**\n# * Indicates if Redis supports Zstd compression.\n# *\n# * @var bool|null\n\
    # */\n# protected $supportsZstd;\n# \n# /**\n# * Prepares the given values to\
    \ be used with the `eval` command, including serialization and compression.\n\
    # *\n# * @param  array<int|string,string>  $values\n# * @return array<int|string,string>"
- name: compressed
  visibility: public
  parameters: []
  comment: '# * Determine if compression is enabled.

    # *

    # * @return bool'
- name: lzfCompressed
  visibility: public
  parameters: []
  comment: '# * Determine if LZF compression is enabled.

    # *

    # * @return bool'
- name: zstdCompressed
  visibility: public
  parameters: []
  comment: '# * Determine if ZSTD compression is enabled.

    # *

    # * @return bool'
- name: lz4Compressed
  visibility: public
  parameters: []
  comment: '# * Determine if LZ4 compression is enabled.

    # *

    # * @return bool'
- name: supportsPacking
  visibility: protected
  parameters: []
  comment: '# * Determine if the current PhpRedis extension version supports packing.

    # *

    # * @return bool'
- name: supportsLzf
  visibility: protected
  parameters: []
  comment: '# * Determine if the current PhpRedis extension version supports LZF compression.

    # *

    # * @return bool'
- name: supportsZstd
  visibility: protected
  parameters: []
  comment: '# * Determine if the current PhpRedis extension version supports Zstd
    compression.

    # *

    # * @return bool'
- name: phpRedisVersionAtLeast
  visibility: protected
  parameters:
  - name: version
  comment: '# * Determine if the PhpRedis extension version is at least the given
    version.

    # *

    # * @param  string  $version

    # * @return bool'
traits:
- Redis
- RuntimeException
- UnexpectedValueException
interfaces: []
