name: Routing
class_comment: null
dependencies: []
properties:
- name: request
  visibility: public
  comment: '# * The request instance.

    # *

    # * @var \Illuminate\Http\Request'
methods:
- name: __construct
  visibility: public
  parameters:
  - name: request
  comment: "# * The request instance.\n# *\n# * @var \\Illuminate\\Http\\Request\n\
    # */\n# public $request;\n# \n# /**\n# * Create a new event instance.\n# *\n#\
    \ * @param  \\Illuminate\\Http\\Request  $request\n# * @return void"
traits: []
interfaces: []
