name: CachesRoutes
class_comment: null
dependencies: []
properties: []
methods:
- name: routesAreCached
  visibility: public
  parameters: []
  comment: '# * Determine if the application routes are cached.

    # *

    # * @return bool'
- name: getCachedRoutesPath
  visibility: public
  parameters: []
  comment: '# * Get the path to the routes cache file.

    # *

    # * @return string'
traits: []
interfaces: []
