name: CachesConfiguration
class_comment: null
dependencies: []
properties: []
methods:
- name: configurationIsCached
  visibility: public
  parameters: []
  comment: '# * Determine if the application configuration is cached.

    # *

    # * @return bool'
- name: getCachedConfigPath
  visibility: public
  parameters: []
  comment: '# * Get the path to the configuration cache file.

    # *

    # * @return string'
- name: getCachedServicesPath
  visibility: public
  parameters: []
  comment: '# * Get the path to the cached services.php file.

    # *

    # * @return string'
traits: []
interfaces: []
