name: platform_exceptions
version: 9.0.0
description: Protevus Platform Exception package
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/exceptions
environment:
  sdk: '>=3.3.0 <4.0.0'
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0