name: platform_exceptions
version: 9.0.0
description: Exception pakcage
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/http_exception
environment:
  sdk: '>=3.3.0 <4.0.0'
dev_dependencies:
  lints: ^4.0.0