name: platform_markdown
version: 8.2.0
description: Platform Markdown view generator. Write static sites, with no build step.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/markdown
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  platform_foundation: ^8.0.0
  file: ^7.0.0
  markdown: ^7.1.0
dev_dependencies:
  platform_testing: ^8.0.0
  lints: ^4.0.0
  test: ^1.24.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_test:
#     path: ../test
#   angel3_websocket:
#     path: ../websocket
#   angel3_client:
#     path: ../client
#   angel3_auth:
#     path: ../auth
#   angel3_validate:
#     path: ../validate