name: FileLocator
class_comment: '# * FileLocator uses the KernelInterface to locate resources in bundles.

  # *

  # * @author Fabien Potencier <fabien@symfony.com>'
dependencies:
- name: BaseFileLocator
  type: class
  source: Symfony\Component\Config\FileLocator
- name: KernelInterface
  type: class
  source: Symfony\Component\HttpKernel\KernelInterface
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: kernel
  comment: null
- name: locate
  visibility: public
  parameters:
  - name: file
  - name: currentPath
    default: 'null'
  - name: first
    default: 'true'
  comment: null
traits:
- Symfony\Component\HttpKernel\KernelInterface
interfaces: []
