name: protevus_openapi
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  protevus_typeforge: ^0.0.1
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
