name: platform_cookie
description: A Dart implementation of Laravel-inspired cookie management for the Protevus platform.
version: 1.0.0
homepage: https://protevus.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  platform_collections: ^8.0.0
  platform_contracts: ^8.0.0
  platform_macroable: ^8.0.0
  platform_support: ^8.0.0

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
