name: illuminate_cookie
description: A Dart implementation of Laravel-inspired cookie management for the Protevus platform.
version: 0.5.1-dev.0+1
homepage: https://protevus.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  illuminate_collections: ^0.5.1-dev.0+1
  illuminate_contracts: ^0.5.1-dev.0+1
  illuminate_macroable: ^0.5.1-dev.0+1
  illuminate_support: ^0.5.1-dev.0+1

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
