name: illuminate_http
description: The Http Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  mime: ^1.0.4
  path: ^1.8.3
  string_scanner: ^1.1.0
  uuid: ^3.0.6
  illuminate_foundation: ^2.0.0
  illuminate_routing: ^0.0.1
  illuminate_validation: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
