name: protevus_http
description: The HTTP Package for the Protevus Platform
version: 1.0.0
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  sanitize_html: ^2.1.0
  email_validator: ^3.0.0
  validator_dart: ^0.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
