name: protevus_http
description: The HTTP Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  protevus_runtime: ^0.0.1
  protevus_openapi: ^0.0.1
  protevus_auth: ^0.0.1
  protevus_database: ^0.0.1
  collection: ^1.18.0
  logging: ^1.2.0
  meta: ^1.12.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
