name: protevus_http
description: The HTTP Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  #path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
