name: platform_framework
version: 9.0.0
description: Protevus Platform high-powered HTTP server extensible framework with dependency injection, routing and much more.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/framework
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  platform_container: ^9.0.0
  platform_exceptions: ^9.0.0
  platform_model: ^9.0.0
  platform_route: ^9.0.0
  platform_mocking: ^9.0.0
  belatuk_merge_map: ^5.1.0
  belatuk_combinator: ^5.1.0
  belatuk_http_server: ^4.1.0
  charcode: ^1.3.0
  file: ^7.0.0
  http_parser: ^4.0.0
  http2: ^2.0.0
  logging: ^1.1.0
  matcher: ^0.12.16
  meta: ^1.9.0
  mime: ^1.0.0
  path: ^1.8.0
  quiver: ^3.2.0
  recase: ^4.1.0
  stack_trace: ^1.11.0
  string_scanner: ^1.2.0
  tuple: ^2.0.0
  uuid: ^4.0.0
  collection: ^1.17.0
dev_dependencies:
  http: ^1.0.0
  io: ^1.0.0
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   platform_container:
#     path: ../container/angel_container
#   platform_http_exception:
#     path: ../http_exception
#   platform_model:
#     path: ../model
#   platform_route:
#     path: ../route
#   platform_mock_request:
#     path: ../mock_request

