name: protevus_platform
repository: https://github.com/protevus/platform
packages:
  - packages/**
  - examples/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    message: "chore: Bump version to %v"
    # Only allow versioning to happen on main branch.
    branch: main
    workspaceChangelog: true
    
ide:
  intellij:
    enabled: false

# Project scripts

scripts:
  analyze:
    run: dart analyze .
    description: Run static analysis on all packages

  test:
    run: melos exec -c 1 --fail-fast -- "dart test"
    description: Run tests for all packages

  format:
    run: dart format .
    description: Format all Dart files in the repository
  
  generate:
    run: melos exec -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run code generation for all packages

  ci:
    run: melos run analyze && melos run test
    description: Run full CI pipeline

  docs:generate:
    run: melos exec -- "dart doc ."
    description: Generate documentation for all packages

  deps:check:
    run: melos exec -- "dart pub outdated"
    description: Check for outdated dependencies

  deps:upgrade:
    run: melos exec -- "dart pub upgrade"
    description: Upgrade all dependencies to their latest versions
  
  publish:
       run: melos publish
       description: Publish all packages that have changed.

  debug_pkg_name:
    run: melos exec -- echo "Package name is {MELOS_PACKAGE_NAME}"
    description: Debug package name resolution
  
  debug_pkg_path:
    run: melos exec -- echo "Package name is {MELOS_PACKAGE_PATH}"
    description: Debug package name resolution
