# Project information
site_name: Protevus
site_description: >-
  Protevus is a unified full-stack platform with an expressive, elegant syntax. 
  We’ve already established the foundation — freeing you to create and deploy across multiple targets 
  all from the same codebase.
site_author: Patrick Stewart
site_url: https://protevus.com/

# Repository
repo_name: protevus/platform
repo_url: https://github.com/protevus/platform
edit_uri: 'https://github.com/protevus/platform/blob/dmz/'

# Custom Directories
docs_dir: docs

# Copyright
copyright: Copyright &copy; 2023 - 2025 Protevus

# Configuration
theme:
  name: material
  custom_dir: website/overrides
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    logo: logo
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - navigation.expand
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - toc.follow
    - announce.dismiss
    - search.highlight
    - search.share
    - search.suggest

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/protevus
    - icon: fontawesome/brands/discord
      link: https://discord.gg/68wNtUEX
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/protevus.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@protevus
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/protevus
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@protevus

extra_css:
  - assets/style.css
extra_javascript:
  - assets/script.js

hooks:
  - website/overrides/hooks/shortcodes.py
  - website/overrides/hooks/translations.py

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.keys
  # - pymdownx.magiclink:
  #     normalize_issue_symbols: true
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - toc:
      permalink: true
  - tables

not_in_nav: |
  /tutorials/**/*.md

nav:
  - Home: index.md
  # - Features: features.md
  
  - Documentation:
    - Documentation: documentation/index.md
    - Prologue:
      - documentation/prologue/release-notes.md
      - documentation/prologue/upgrade-guide.md
      - documentation/prologue/contributing-guide.md
    - Getting Started:
      - documentation/getting-started/installation.md
      - documentation/getting-started/configuration.md
      - documentation/getting-started/directory-structure.md
      - documentation/getting-started/frontend.md
      - documentation/getting-started/starter-kits.md
      - documentation/getting-started/deployment.md
    - Architecture Concepts:
      - documentation/architecture-concepts/isolate.md
      - documentation/architecture-concepts/request-lifecycle.md
      - documentation/architecture-concepts/service-container.md
      - documentation/architecture-concepts/services.md
      - documentation/architecture-concepts/facades.md
    - The Basics:
      - documentation/the-basic/routing.md
      - documentation/the-basic/middleware.md
      - documentation/the-basic/csrf-protection.md
      - documentation/the-basic/controller.md
      - documentation/the-basic/request.md
      - documentation/the-basic/response.md
      - documentation/the-basic/views.md
      - Template Engines:
        - documentation/the-basic/template-engines/blade-templates.md
        - documentation/the-basic/template-engines/jinja-templates.md
        - documentation/the-basic/template-engines/jael-templates.md
        - documentation/the-basic/template-engines/mustache-templates.md
      - documentation/the-basic/asset-bundling.md
      - documentation/the-basic/url-generation.md
      - documentation/the-basic/session.md
      - documentation/the-basic/validation.md
      - documentation/the-basic/error-handling.md
      - documentation/the-basic/logging.md
    - Digging Deeper:
      - documentation/digging-deeper/artisan-console.md
      - documentation/digging-deeper/broadcasting.md
      - documentation/digging-deeper/cache.md
      - documentation/digging-deeper/collections.md
      - documentation/digging-deeper/concurrency.md
      - documentation/digging-deeper/context.md
      - documentation/digging-deeper/contracts.md
      - documentation/digging-deeper/events.md
      - documentation/digging-deeper/file-storage.md
      - documentation/digging-deeper/helpers.md
      - documentation/digging-deeper/http-client.md
      - documentation/digging-deeper/localization.md
      - documentation/digging-deeper/mail.md
      - documentation/digging-deeper/notifications.md
      - documentation/digging-deeper/package-development.md
      - documentation/digging-deeper/processes.md
      - documentation/digging-deeper/queues.md
      - documentation/digging-deeper/rate-limiting.md
      - documentation/digging-deeper/strings.md
      - documentation/digging-deeper/task-scheduling.md
      - documentation/digging-deeper/env.md
      - documentation/digging-deeper/websocket.md
    - Security:
      - documentation/security/authentication.md
      - documentation/security/cors.md
      - documentation/security/encryption.md
      - documentation/security/hashing.md
    - Database:
      - documentation/database/migration.md
      - documentation/database/query-builder.md
      - Model:
        - documentation/database/model/index.md
      - Relationship:
        - documentation/database/model/relationship/has-one.md
        - documentation/database/model/relationship/has-many.md
        - documentation/database/model/relationship/belongs-to.md
        - documentation/database/model/relationship/many-to-many.md
        - documentation/database/model/serializer.md
    - Eloquent ORM:
      - documentation/eloquent-orm/index.md
    - Testing:
      - documentation/testing/index.md
      - documentation/testing/testing.md
    - Packages:
      - documentation/packages/index.md
    - Examples:
      - documentation/examples/index.md
    - API Documentation:
      - documentation/api-documentation/index.md
  - Ecosystem:
    - ecosystem/index.md
  - Developers:
    - developers/index.md
    - developers/contribute.md
    - developers/forking-repos.md
    - developers/bug-report.md
    - developers/failing-test.md
    - developers/doc-report.md
    - developers/feature-request.md
    - developers/enhancement-request.md
    - developers/translations.md
    - developers/pull-request.md
    - developers/questions-support.md
    - developers/security-report.md
    - Guides:
      - Package Development: developers/guides/package-development.md
  # - Insiders:
  #   - insiders/index.md
  #   - insiders/why-sponsor.md
  #   - insiders/whats-in-it.md
  #   - insiders/who-is-sponsoring.md
  #   - insiders/sponsoring-tiers.md
  #   - insiders/how-to-sponsor.md
  #   - Additional Information:
  #     - insiders/payment-billing.md
  #     - insiders/access-management.md
  #     - insiders/runtime-cancellations.md
  #     - insiders/privacy.md
  #     - insiders/license.md
  #     - insiders/support.md
  #   - Using Insiders:
  #     - insiders/getting-started.md
  #     - insiders/changelog.md
  #     - insiders/upgrade.md
  - Releases:
      - releases/index.md
      - releases/release-process.md
      - 0.5.1-dev: releases/notes/v0.5.1-dev.md
      - 0.5.0-dev: releases/notes/v0.5.0-dev.md
      - 0.4.0-dev: releases/notes/v0.4.0-dev.md
      - 0.3.0-dev: releases/notes/v0.3.0-dev.md
      - 0.2.0-dev: releases/notes/v0.2.0-dev.md
      - 0.1.0-dev: releases/notes/v0.1.0-dev.md
  - Roadmaps:
    - notes/index.md
    - Authentication: notes/auth_dev_notes.md
    - Broadcasting: notes/broadcasting_dev_notes.md
    - Builder: notes/builder_dev_notes.md
    - Bus: notes/bus_dev_notes.md
    - Cache: notes/cache_dev_notes.md
    - CLI: notes/cli_dev_notes.md
    - Collections: notes/collections_dev_notes.md
    - Concurrency: notes/concurrency_dev_notes.md
    - Conditionable: notes/conditionable_dev_notes.md
    - Config: notes/config_dev_notes.md
    - Console: notes/console_dev_notes.md
    - Container: notes/container_dev_notes.md
    - Contracts: notes/contracts_dev_notes.md
    - Cookie: notes/cookie_dev_notes.md
    - Database: notes/database_dev_notes.md
    - DBO: notes/dbo_dev_notes.md
    - Encryption: notes/encryption_dev_notes.md
    - Events: notes/events_dev_notes.md
    - Filesystem: notes/filesystem_dev_notes.md
    - Foundation: notes/foundation_dev_notes.md
    - Hashing: notes/hashing_dev_notes.md
    - HTTP: notes/http_dev_notes.md
    - Log: notes/log_dev_notes.md
    - Macroable: notes/macroable_dev_notes.md
    - Mail: notes/mail_dev_notes.md
    - Migration: notes/migration_dev_notes.md
    - Mirrors: notes/mirrors_dev_notes.md
    - Notifications: notes/notifications_dev_notes.md
    - Pagination: notes/pagination_dev_notes.md
    - Pipeline: notes/pipeline_dev_notes.md
    - Process: notes/process_dev_notes.md
    - Queue: notes/queue_dev_notes.md
    - Routing: notes/routing_dev_notes.md
    - Session: notes/session_dev_notes.md
    - Storage: notes/storage_dev_notes.md
    - Support: notes/support_dev_notes.md
    - Testing: notes/testing_dev_notes.md
    - Translation: notes/translation_dev_notes.md
    - Validation: notes/validation_dev_notes.md
    - View: notes/view_dev_notes.md
    - Websocket: notes/websocket_dev_notes.md
  - Blog:
    - blog/index.md
