name: protevus_platform
description: The Protevus Platform
version: 1.0.0
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platform

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  melos: ^6.1.0
  test: ^1.24.0