name: protevus_platform
description: The Protevus Platform
version: 9.0.0
homepage: https://protevus.com
documentation: https://protevus.com
repository: https://github.com/protevus/platform

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^4.0.0
  melos: ^6.2.0
  test: ^1.25.8
  yaml: ^3.1.2
  args: ^2.6.0
  yaml_edit: ^2.2.1