name: fabric_framework
description: The Fabric Framework
version: 1.0.0
homepage: https://vieo.dev/fabric
documentation: https://vieo.dev/fabric/docs
repository: https://github.com/vieolab/framework

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0