name: Configuration
class_comment: '# * This class contains the configuration information for the bundle.

  # *

  # * This information is solely responsible for how the different configuration

  # * sections are normalized, and merged.

  # *

  # * @author Fabien Potencier <fabien@symfony.com>'
dependencies:
- name: TreeBuilder
  type: class
  source: Symfony\Component\Config\Definition\Builder\TreeBuilder
- name: ConfigurationInterface
  type: class
  source: Symfony\Component\Config\Definition\ConfigurationInterface
properties: []
methods:
- name: getConfigTreeBuilder
  visibility: public
  parameters: []
  comment: '# * This class contains the configuration information for the bundle.

    # *

    # * This information is solely responsible for how the different configuration

    # * sections are normalized, and merged.

    # *

    # * @author Fabien Potencier <fabien@symfony.com>

    # */

    # class Configuration implements ConfigurationInterface

    # {

    # /**

    # * Generates the configuration tree builder.'
traits:
- Symfony\Component\Config\Definition\Builder\TreeBuilder
- Symfony\Component\Config\Definition\ConfigurationInterface
interfaces:
- ConfigurationInterface
