name: platform_container
version: 9.0.0
description: Protevus Platform hierarchical DI container, and pluggable backends for reflection.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/container/container
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  collection: ^1.17.0
  quiver: ^3.2.0
dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0