name: dsr_container
description: A PSR-11 compatible container interface for Dart. Provides standardized interfaces for dependency injection containers including ContainerInterface and related exceptions.
version: 0.0.1
homepage: https://dart-fig.org

environment:
  sdk: ^3.4.2

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
