name: console
class_comment: null
dependencies:
- name: DebugCommand
  type: class
  source: Symfony\Bridge\Twig\Command\DebugCommand
- name: LintCommand
  type: class
  source: Symfony\Bundle\TwigBundle\Command\LintCommand
properties: []
methods: []
traits:
- Symfony\Bridge\Twig\Command\DebugCommand
- Symfony\Bundle\TwigBundle\Command\LintCommand
interfaces: []
