name: importmap
class_comment: null
dependencies:
- name: ImportMapExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\ImportMapExtension
- name: ImportMapRuntime
  type: class
  source: Symfony\Bridge\Twig\Extension\ImportMapRuntime
properties: []
methods: []
traits:
- Symfony\Bridge\Twig\Extension\ImportMapExtension
- Symfony\Bridge\Twig\Extension\ImportMapRuntime
interfaces: []
