name: mailer
class_comment: null
dependencies:
- name: BodyRenderer
  type: class
  source: Symfony\Bridge\Twig\Mime\BodyRenderer
- name: MessageListener
  type: class
  source: Symfony\Component\Mailer\EventListener\MessageListener
- name: BodyRendererInterface
  type: class
  source: Symfony\Component\Mime\BodyRendererInterface
properties: []
methods: []
traits:
- Symfony\Bridge\Twig\Mime\BodyRenderer
- Symfony\Component\Mailer\EventListener\MessageListener
- Symfony\Component\Mime\BodyRendererInterface
interfaces: []
