name: twig
class_comment: null
dependencies:
- name: ContainerInterface
  type: class
  source: Psr\Container\ContainerInterface
- name: AppVariable
  type: class
  source: Symfony\Bridge\Twig\AppVariable
- name: TwigDataCollector
  type: class
  source: Symfony\Bridge\Twig\DataCollector\TwigDataCollector
- name: TwigErrorRenderer
  type: class
  source: Symfony\Bridge\Twig\ErrorRenderer\TwigErrorRenderer
- name: TemplateAttributeListener
  type: class
  source: Symfony\Bridge\Twig\EventListener\TemplateAttributeListener
- name: AssetExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\AssetExtension
- name: EmojiExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\EmojiExtension
- name: ExpressionExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\ExpressionExtension
- name: HtmlSanitizerExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\HtmlSanitizerExtension
- name: HttpFoundationExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\HttpFoundationExtension
- name: HttpKernelExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\HttpKernelExtension
- name: HttpKernelRuntime
  type: class
  source: Symfony\Bridge\Twig\Extension\HttpKernelRuntime
- name: ProfilerExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\ProfilerExtension
- name: RoutingExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\RoutingExtension
- name: SerializerExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\SerializerExtension
- name: SerializerRuntime
  type: class
  source: Symfony\Bridge\Twig\Extension\SerializerRuntime
- name: StopwatchExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\StopwatchExtension
- name: TranslationExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\TranslationExtension
- name: WebLinkExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\WebLinkExtension
- name: WorkflowExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\WorkflowExtension
- name: YamlExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\YamlExtension
- name: TwigExtractor
  type: class
  source: Symfony\Bridge\Twig\Translation\TwigExtractor
- name: TemplateCacheWarmer
  type: class
  source: Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer
- name: EnvironmentConfigurator
  type: class
  source: Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator
- name: TemplateIterator
  type: class
  source: Symfony\Bundle\TwigBundle\TemplateIterator
- name: FilesystemCache
  type: class
  source: Twig\Cache\FilesystemCache
- name: Environment
  type: class
  source: Twig\Environment
- name: CoreExtension
  type: class
  source: Twig\Extension\CoreExtension
- name: DebugExtension
  type: class
  source: Twig\Extension\DebugExtension
- name: EscaperExtension
  type: class
  source: Twig\Extension\EscaperExtension
- name: OptimizerExtension
  type: class
  source: Twig\Extension\OptimizerExtension
- name: StagingExtension
  type: class
  source: Twig\Extension\StagingExtension
- name: ExtensionSet
  type: class
  source: Twig\ExtensionSet
- name: ChainLoader
  type: class
  source: Twig\Loader\ChainLoader
- name: FilesystemLoader
  type: class
  source: Twig\Loader\FilesystemLoader
- name: Profile
  type: class
  source: Twig\Profiler\Profile
- name: ContainerRuntimeLoader
  type: class
  source: Twig\RuntimeLoader\ContainerRuntimeLoader
- name: Template
  type: class
  source: Twig\Template
- name: TemplateWrapper
  type: class
  source: Twig\TemplateWrapper
properties: []
methods: []
traits:
- Psr\Container\ContainerInterface
- Symfony\Bridge\Twig\AppVariable
- Symfony\Bridge\Twig\DataCollector\TwigDataCollector
- Symfony\Bridge\Twig\ErrorRenderer\TwigErrorRenderer
- Symfony\Bridge\Twig\EventListener\TemplateAttributeListener
- Symfony\Bridge\Twig\Extension\AssetExtension
- Symfony\Bridge\Twig\Extension\EmojiExtension
- Symfony\Bridge\Twig\Extension\ExpressionExtension
- Symfony\Bridge\Twig\Extension\HtmlSanitizerExtension
- Symfony\Bridge\Twig\Extension\HttpFoundationExtension
- Symfony\Bridge\Twig\Extension\HttpKernelExtension
- Symfony\Bridge\Twig\Extension\HttpKernelRuntime
- Symfony\Bridge\Twig\Extension\ProfilerExtension
- Symfony\Bridge\Twig\Extension\RoutingExtension
- Symfony\Bridge\Twig\Extension\SerializerExtension
- Symfony\Bridge\Twig\Extension\SerializerRuntime
- Symfony\Bridge\Twig\Extension\StopwatchExtension
- Symfony\Bridge\Twig\Extension\TranslationExtension
- Symfony\Bridge\Twig\Extension\WebLinkExtension
- Symfony\Bridge\Twig\Extension\WorkflowExtension
- Symfony\Bridge\Twig\Extension\YamlExtension
- Symfony\Bridge\Twig\Translation\TwigExtractor
- Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer
- Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator
- Symfony\Bundle\TwigBundle\TemplateIterator
- Twig\Cache\FilesystemCache
- Twig\Environment
- Twig\Extension\CoreExtension
- Twig\Extension\DebugExtension
- Twig\Extension\EscaperExtension
- Twig\Extension\OptimizerExtension
- Twig\Extension\StagingExtension
- Twig\ExtensionSet
- Twig\Loader\ChainLoader
- Twig\Loader\FilesystemLoader
- Twig\Profiler\Profile
- Twig\RuntimeLoader\ContainerRuntimeLoader
- Twig\Template
- Twig\TemplateWrapper
interfaces: []
