name: illuminate_routing
description: The Routing Package for the Protevus Platform
version: 0.5.1-dev.0+1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  illuminate_contracts: ^0.5.1-dev.0+1
  illuminate_foundation: ^0.5.1-dev.0+1
  illuminate_http: ^0.5.1-dev.0+1
  illuminate_support: ^0.5.1-dev.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
