name: illuminate_routing
description: The Routing Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  illuminate_foundation: ^2.0.0
  illuminate_http: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
