name: ConfigShowCommand
class_comment: null
dependencies:
- name: Command
  type: class
  source: Illuminate\Console\Command
- name: Arr
  type: class
  source: Illuminate\Support\Arr
- name: AsCommand
  type: class
  source: Symfony\Component\Console\Attribute\AsCommand
properties:
- name: signature
  visibility: protected
  comment: '# * The console command signature.

    # *

    # * @var string'
- name: description
  visibility: protected
  comment: '# * The console command description.

    # *

    # * @var string'
methods:
- name: handle
  visibility: public
  parameters: []
  comment: "# * The console command signature.\n# *\n# * @var string\n# */\n# protected\
    \ $signature = 'config:show {config : The configuration file or key to show}';\n\
    # \n# /**\n# * The console command description.\n# *\n# * @var string\n# */\n\
    # protected $description = 'Display all of the values for a given configuration\
    \ file or key';\n# \n# /**\n# * Execute the console command.\n# *\n# * @return\
    \ int"
- name: render
  visibility: public
  parameters:
  - name: name
  comment: '# * Render the configuration values.

    # *

    # * @param  string  $name

    # * @return void'
- name: title
  visibility: public
  parameters:
  - name: title
  - name: subtitle
    default: 'null'
  comment: '# * Render the title.

    # *

    # * @param  string  $title

    # * @param  string|null  $subtitle

    # * @return void'
- name: formatKey
  visibility: protected
  parameters:
  - name: key
  comment: '# * Format the given configuration key.

    # *

    # * @param  string  $key

    # * @return string'
- name: formatValue
  visibility: protected
  parameters:
  - name: value
  comment: '# * Format the given configuration value.

    # *

    # * @param  mixed  $value

    # * @return string'
traits:
- Illuminate\Console\Command
- Illuminate\Support\Arr
- Symfony\Component\Console\Attribute\AsCommand
interfaces: []
