name: ConfigPublishCommand
class_comment: null
dependencies:
- name: Command
  type: class
  source: Illuminate\Console\Command
- name: AsCommand
  type: class
  source: Symfony\Component\Console\Attribute\AsCommand
- name: Finder
  type: class
  source: Symfony\Component\Finder\Finder
properties:
- name: signature
  visibility: protected
  comment: '# * The name and signature of the console command.

    # *

    # * @var string'
- name: description
  visibility: protected
  comment: '# * The console command description.

    # *

    # * @var string'
methods:
- name: handle
  visibility: public
  parameters: []
  comment: "# * The name and signature of the console command.\n# *\n# * @var string\n\
    # */\n# protected $signature = 'config:publish\n# {name? : The name of the configuration\
    \ file to publish}\n# {--all : Publish all configuration files}\n# {--force :\
    \ Overwrite any existing configuration files}';\n# \n# /**\n# * The console command\
    \ description.\n# *\n# * @var string\n# */\n# protected $description = 'Publish\
    \ configuration files to your application';\n# \n# /**\n# * Execute the console\
    \ command.\n# *\n# * @return int"
- name: publish
  visibility: protected
  parameters:
  - name: name
  - name: file
  - name: destination
  comment: '# * Publish the given file to the given destination.

    # *

    # * @param  string  $name

    # * @param  string  $file

    # * @param  string  $destination

    # * @return void'
- name: getBaseConfigurationFiles
  visibility: protected
  parameters: []
  comment: '# * Get an array containing the base configuration files.

    # *

    # * @return array'
traits:
- Illuminate\Console\Command
- Symfony\Component\Console\Attribute\AsCommand
- Symfony\Component\Finder\Finder
interfaces: []
