name: EnvironmentEncryptCommand
class_comment: null
dependencies:
- name: Exception
  type: class
  source: Exception
- name: Command
  type: class
  source: Illuminate\Console\Command
- name: Encrypter
  type: class
  source: Illuminate\Encryption\Encrypter
- name: Filesystem
  type: class
  source: Illuminate\Filesystem\Filesystem
- name: Str
  type: class
  source: Illuminate\Support\Str
- name: AsCommand
  type: class
  source: Symfony\Component\Console\Attribute\AsCommand
properties:
- name: signature
  visibility: protected
  comment: '# * The name and signature of the console command.

    # *

    # * @var string'
- name: description
  visibility: protected
  comment: '# * The console command description.

    # *

    # * @var string'
- name: files
  visibility: protected
  comment: '# * The filesystem instance.

    # *

    # * @var \Illuminate\Filesystem\Filesystem'
methods:
- name: __construct
  visibility: public
  parameters:
  - name: files
  comment: "# * The name and signature of the console command.\n# *\n# * @var string\n\
    # */\n# protected $signature = 'env:encrypt\n# {--key= : The encryption key}\n\
    # {--cipher= : The encryption cipher}\n# {--env= : The environment to be encrypted}\n\
    # {--prune : Delete the original environment file}\n# {--force : Overwrite the\
    \ existing encrypted environment file}';\n# \n# /**\n# * The console command description.\n\
    # *\n# * @var string\n# */\n# protected $description = 'Encrypt an environment\
    \ file';\n# \n# /**\n# * The filesystem instance.\n# *\n# * @var \\Illuminate\\\
    Filesystem\\Filesystem\n# */\n# protected $files;\n# \n# /**\n# * Create a new\
    \ command instance.\n# *\n# * @param  \\Illuminate\\Filesystem\\Filesystem  $files\n\
    # * @return void"
- name: handle
  visibility: public
  parameters: []
  comment: '# * Execute the console command.

    # *

    # * @return void'
- name: parseKey
  visibility: protected
  parameters:
  - name: key
  comment: '# * Parse the encryption key.

    # *

    # * @param  string  $key

    # * @return string'
traits:
- Exception
- Illuminate\Console\Command
- Illuminate\Encryption\Encrypter
- Illuminate\Filesystem\Filesystem
- Illuminate\Support\Str
- Symfony\Component\Console\Attribute\AsCommand
interfaces: []
