name: console
class_comment: null
dependencies:
- name: UserPasswordHashCommand
  type: class
  source: Symfony\Component\PasswordHasher\Command\UserPasswordHashCommand
properties: []
methods: []
traits:
- Symfony\Component\PasswordHasher\Command\UserPasswordHashCommand
interfaces: []
