name: debug_console
class_comment: null
dependencies:
- name: DebugFirewallCommand
  type: class
  source: Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
properties: []
methods: []
traits:
- Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
interfaces: []
