name: password_hasher
class_comment: null
dependencies:
- name: FormType
  type: class
  source: Symfony\Component\Form\Extension\Core\Type\FormType
- name: PasswordType
  type: class
  source: Symfony\Component\Form\Extension\Core\Type\PasswordType
- name: PasswordHasherListener
  type: class
  source: Symfony\Component\Form\Extension\PasswordHasher\EventListener\PasswordHasherListener
- name: FormTypePasswordHasherExtension
  type: class
  source: Symfony\Component\Form\Extension\PasswordHasher\Type\FormTypePasswordHasherExtension
- name: PasswordTypePasswordHasherExtension
  type: class
  source: Symfony\Component\Form\Extension\PasswordHasher\Type\PasswordTypePasswordHasherExtension
- name: PasswordHasherFactory
  type: class
  source: Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory
- name: PasswordHasherFactoryInterface
  type: class
  source: Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface
- name: UserPasswordHasher
  type: class
  source: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher
- name: UserPasswordHasherInterface
  type: class
  source: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface
properties: []
methods: []
traits:
- Symfony\Component\Form\Extension\Core\Type\FormType
- Symfony\Component\Form\Extension\Core\Type\PasswordType
- Symfony\Component\Form\Extension\PasswordHasher\EventListener\PasswordHasherListener
- Symfony\Component\Form\Extension\PasswordHasher\Type\FormTypePasswordHasherExtension
- Symfony\Component\Form\Extension\PasswordHasher\Type\PasswordTypePasswordHasherExtension
- Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory
- Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface
- Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher
- Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface
interfaces: []
