name: security_authenticator_login_link
class_comment: null
dependencies:
- name: FirewallAwareLoginLinkHandler
  type: class
  source: Symfony\Bundle\SecurityBundle\LoginLink\FirewallAwareLoginLinkHandler
- name: Parameter
  type: class
  source: Symfony\Component\DependencyInjection\Parameter
- name: ExpiredSignatureStorage
  type: class
  source: Symfony\Component\Security\Core\Signature\ExpiredSignatureStorage
- name: SignatureHasher
  type: class
  source: Symfony\Component\Security\Core\Signature\SignatureHasher
- name: LoginLinkAuthenticator
  type: class
  source: Symfony\Component\Security\Http\Authenticator\LoginLinkAuthenticator
- name: LoginLinkHandler
  type: class
  source: Symfony\Component\Security\Http\LoginLink\LoginLinkHandler
- name: LoginLinkHandlerInterface
  type: class
  source: Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface
properties: []
methods: []
traits:
- Symfony\Bundle\SecurityBundle\LoginLink\FirewallAwareLoginLinkHandler
- Symfony\Component\DependencyInjection\Parameter
- Symfony\Component\Security\Core\Signature\ExpiredSignatureStorage
- Symfony\Component\Security\Core\Signature\SignatureHasher
- Symfony\Component\Security\Http\Authenticator\LoginLinkAuthenticator
- Symfony\Component\Security\Http\LoginLink\LoginLinkHandler
- Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface
interfaces: []
