name: security_authenticator_remember_me
class_comment: null
dependencies:
- name: FirewallAwareRememberMeHandler
  type: class
  source: Symfony\Bundle\SecurityBundle\RememberMe\FirewallAwareRememberMeHandler
- name: Parameter
  type: class
  source: Symfony\Component\DependencyInjection\Parameter
- name: SignatureHasher
  type: class
  source: Symfony\Component\Security\Core\Signature\SignatureHasher
- name: RememberMeAuthenticator
  type: class
  source: Symfony\Component\Security\Http\Authenticator\RememberMeAuthenticator
- name: CheckRememberMeConditionsListener
  type: class
  source: Symfony\Component\Security\Http\EventListener\CheckRememberMeConditionsListener
- name: RememberMeListener
  type: class
  source: Symfony\Component\Security\Http\EventListener\RememberMeListener
- name: PersistentRememberMeHandler
  type: class
  source: Symfony\Component\Security\Http\RememberMe\PersistentRememberMeHandler
- name: RememberMeHandlerInterface
  type: class
  source: Symfony\Component\Security\Http\RememberMe\RememberMeHandlerInterface
- name: ResponseListener
  type: class
  source: Symfony\Component\Security\Http\RememberMe\ResponseListener
- name: SignatureRememberMeHandler
  type: class
  source: Symfony\Component\Security\Http\RememberMe\SignatureRememberMeHandler
properties: []
methods: []
traits:
- Symfony\Bundle\SecurityBundle\RememberMe\FirewallAwareRememberMeHandler
- Symfony\Component\DependencyInjection\Parameter
- Symfony\Component\Security\Core\Signature\SignatureHasher
- Symfony\Component\Security\Http\Authenticator\RememberMeAuthenticator
- Symfony\Component\Security\Http\EventListener\CheckRememberMeConditionsListener
- Symfony\Component\Security\Http\EventListener\RememberMeListener
- Symfony\Component\Security\Http\RememberMe\PersistentRememberMeHandler
- Symfony\Component\Security\Http\RememberMe\RememberMeHandlerInterface
- Symfony\Component\Security\Http\RememberMe\ResponseListener
- Symfony\Component\Security\Http\RememberMe\SignatureRememberMeHandler
interfaces: []
