name: security_listeners
class_comment: null
dependencies:
- name: ServiceLocator
  type: class
  source: Symfony\Component\DependencyInjection\ServiceLocator
- name: AccessMap
  type: class
  source: Symfony\Component\Security\Http\AccessMap
- name: CustomAuthenticationFailureHandler
  type: class
  source: Symfony\Component\Security\Http\Authentication\CustomAuthenticationFailureHandler
- name: CustomAuthenticationSuccessHandler
  type: class
  source: Symfony\Component\Security\Http\Authentication\CustomAuthenticationSuccessHandler
- name: DefaultAuthenticationFailureHandler
  type: class
  source: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler
- name: DefaultAuthenticationSuccessHandler
  type: class
  source: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
- name: ClearSiteDataLogoutListener
  type: class
  source: Symfony\Component\Security\Http\EventListener\ClearSiteDataLogoutListener
- name: CookieClearingLogoutListener
  type: class
  source: Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener
- name: DefaultLogoutListener
  type: class
  source: Symfony\Component\Security\Http\EventListener\DefaultLogoutListener
- name: SessionLogoutListener
  type: class
  source: Symfony\Component\Security\Http\EventListener\SessionLogoutListener
- name: AccessListener
  type: class
  source: Symfony\Component\Security\Http\Firewall\AccessListener
- name: ChannelListener
  type: class
  source: Symfony\Component\Security\Http\Firewall\ChannelListener
- name: ContextListener
  type: class
  source: Symfony\Component\Security\Http\Firewall\ContextListener
- name: ExceptionListener
  type: class
  source: Symfony\Component\Security\Http\Firewall\ExceptionListener
- name: LogoutListener
  type: class
  source: Symfony\Component\Security\Http\Firewall\LogoutListener
- name: SwitchUserListener
  type: class
  source: Symfony\Component\Security\Http\Firewall\SwitchUserListener
properties: []
methods: []
traits:
- Symfony\Component\DependencyInjection\ServiceLocator
- Symfony\Component\Security\Http\AccessMap
- Symfony\Component\Security\Http\Authentication\CustomAuthenticationFailureHandler
- Symfony\Component\Security\Http\Authentication\CustomAuthenticationSuccessHandler
- Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler
- Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
- Symfony\Component\Security\Http\EventListener\ClearSiteDataLogoutListener
- Symfony\Component\Security\Http\EventListener\CookieClearingLogoutListener
- Symfony\Component\Security\Http\EventListener\DefaultLogoutListener
- Symfony\Component\Security\Http\EventListener\SessionLogoutListener
- Symfony\Component\Security\Http\Firewall\AccessListener
- Symfony\Component\Security\Http\Firewall\ChannelListener
- Symfony\Component\Security\Http\Firewall\ContextListener
- Symfony\Component\Security\Http\Firewall\ExceptionListener
- Symfony\Component\Security\Http\Firewall\LogoutListener
- Symfony\Component\Security\Http\Firewall\SwitchUserListener
interfaces: []
