name: security
class_comment: null
dependencies:
- name: ExpressionCacheWarmer
  type: class
  source: Symfony\Bundle\SecurityBundle\CacheWarmer\ExpressionCacheWarmer
- name: FirewallListener
  type: class
  source: Symfony\Bundle\SecurityBundle\EventListener\FirewallListener
- name: LogoutRouteLoader
  type: class
  source: Symfony\Bundle\SecurityBundle\Routing\LogoutRouteLoader
- name: Security
  type: class
  source: Symfony\Bundle\SecurityBundle\Security
- name: FirewallConfig
  type: class
  source: Symfony\Bundle\SecurityBundle\Security\FirewallConfig
- name: FirewallContext
  type: class
  source: Symfony\Bundle\SecurityBundle\Security\FirewallContext
- name: FirewallMap
  type: class
  source: Symfony\Bundle\SecurityBundle\Security\FirewallMap
- name: LazyFirewallContext
  type: class
  source: Symfony\Bundle\SecurityBundle\Security\LazyFirewallContext
- name: ServiceLocator
  type: class
  source: Symfony\Component\DependencyInjection\ServiceLocator
- name: BaseExpressionLanguage
  type: class
  source: Symfony\Component\ExpressionLanguage\ExpressionLanguage
- name: LdapUserProvider
  type: class
  source: Symfony\Component\Ldap\Security\LdapUserProvider
- name: AuthenticationTrustResolver
  type: class
  source: Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver
- name: TokenStorage
  type: class
  source: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
- name: TokenStorageInterface
  type: class
  source: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface
- name: UsageTrackingTokenStorage
  type: class
  source: Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage
- name: AccessDecisionManager
  type: class
  source: Symfony\Component\Security\Core\Authorization\AccessDecisionManager
- name: AccessDecisionManagerInterface
  type: class
  source: Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface
- name: AuthorizationChecker
  type: class
  source: Symfony\Component\Security\Core\Authorization\AuthorizationChecker
- name: AuthorizationCheckerInterface
  type: class
  source: Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface
- name: ExpressionLanguage
  type: class
  source: Symfony\Component\Security\Core\Authorization\ExpressionLanguage
- name: AuthenticatedVoter
  type: class
  source: Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter
- name: ExpressionVoter
  type: class
  source: Symfony\Component\Security\Core\Authorization\Voter\ExpressionVoter
- name: RoleHierarchyVoter
  type: class
  source: Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter
- name: RoleVoter
  type: class
  source: Symfony\Component\Security\Core\Authorization\Voter\RoleVoter
- name: RoleHierarchy
  type: class
  source: Symfony\Component\Security\Core\Role\RoleHierarchy
- name: RoleHierarchyInterface
  type: class
  source: Symfony\Component\Security\Core\Role\RoleHierarchyInterface
- name: ChainUserProvider
  type: class
  source: Symfony\Component\Security\Core\User\ChainUserProvider
- name: InMemoryUserChecker
  type: class
  source: Symfony\Component\Security\Core\User\InMemoryUserChecker
- name: InMemoryUserProvider
  type: class
  source: Symfony\Component\Security\Core\User\InMemoryUserProvider
- name: MissingUserProvider
  type: class
  source: Symfony\Component\Security\Core\User\MissingUserProvider
- name: UserPasswordValidator
  type: class
  source: Symfony\Component\Security\Core\Validator\Constraints\UserPasswordValidator
- name: AuthenticationUtils
  type: class
  source: Symfony\Component\Security\Http\Authentication\AuthenticationUtils
- name: SecurityTokenValueResolver
  type: class
  source: Symfony\Component\Security\Http\Controller\SecurityTokenValueResolver
- name: UserValueResolver
  type: class
  source: Symfony\Component\Security\Http\Controller\UserValueResolver
- name: IsGrantedAttributeListener
  type: class
  source: Symfony\Component\Security\Http\EventListener\IsGrantedAttributeListener
- name: Firewall
  type: class
  source: Symfony\Component\Security\Http\Firewall
- name: FirewallMapInterface
  type: class
  source: Symfony\Component\Security\Http\FirewallMapInterface
- name: HttpUtils
  type: class
  source: Symfony\Component\Security\Http\HttpUtils
- name: ImpersonateUrlGenerator
  type: class
  source: Symfony\Component\Security\Http\Impersonate\ImpersonateUrlGenerator
- name: LogoutUrlGenerator
  type: class
  source: Symfony\Component\Security\Http\Logout\LogoutUrlGenerator
- name: SessionAuthenticationStrategy
  type: class
  source: Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy
- name: SessionAuthenticationStrategyInterface
  type: class
  source: Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface
properties: []
methods: []
traits:
- Symfony\Bundle\SecurityBundle\CacheWarmer\ExpressionCacheWarmer
- Symfony\Bundle\SecurityBundle\EventListener\FirewallListener
- Symfony\Bundle\SecurityBundle\Routing\LogoutRouteLoader
- Symfony\Bundle\SecurityBundle\Security
- Symfony\Bundle\SecurityBundle\Security\FirewallConfig
- Symfony\Bundle\SecurityBundle\Security\FirewallContext
- Symfony\Bundle\SecurityBundle\Security\FirewallMap
- Symfony\Bundle\SecurityBundle\Security\LazyFirewallContext
- Symfony\Component\DependencyInjection\ServiceLocator
- Symfony\Component\Ldap\Security\LdapUserProvider
- Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver
- Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage
- Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface
- Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage
- Symfony\Component\Security\Core\Authorization\AccessDecisionManager
- Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface
- Symfony\Component\Security\Core\Authorization\AuthorizationChecker
- Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface
- Symfony\Component\Security\Core\Authorization\ExpressionLanguage
- Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter
- Symfony\Component\Security\Core\Authorization\Voter\ExpressionVoter
- Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter
- Symfony\Component\Security\Core\Authorization\Voter\RoleVoter
- Symfony\Component\Security\Core\Role\RoleHierarchy
- Symfony\Component\Security\Core\Role\RoleHierarchyInterface
- Symfony\Component\Security\Core\User\ChainUserProvider
- Symfony\Component\Security\Core\User\InMemoryUserChecker
- Symfony\Component\Security\Core\User\InMemoryUserProvider
- Symfony\Component\Security\Core\User\MissingUserProvider
- Symfony\Component\Security\Core\Validator\Constraints\UserPasswordValidator
- Symfony\Component\Security\Http\Authentication\AuthenticationUtils
- Symfony\Component\Security\Http\Controller\SecurityTokenValueResolver
- Symfony\Component\Security\Http\Controller\UserValueResolver
- Symfony\Component\Security\Http\EventListener\IsGrantedAttributeListener
- Symfony\Component\Security\Http\Firewall
- Symfony\Component\Security\Http\FirewallMapInterface
- Symfony\Component\Security\Http\HttpUtils
- Symfony\Component\Security\Http\Impersonate\ImpersonateUrlGenerator
- Symfony\Component\Security\Http\Logout\LogoutUrlGenerator
- Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy
- Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface
interfaces: []
