services:
  databases:
    postgres:
      category: databases
      version: 14
      enabled: false
      config:
        port: 5432
        max_connections: 100
        shared_buffers: 256MB
    mysql:
      category: databases
      version: 8.0
      enabled: false
      config:
        port: 3306
        max_connections: 100
    mongodb:
      category: databases
      version: 5.0
      enabled: false
      config:
        port: 27017
        storage_engine: wiredTiger
    mariadb:
      category: databases
      version: 10.6
      enabled: false
      config:
        port: 3306
        max_connections: 100
    mssql:
      category: databases
      version: 2019
      enabled: false
      config:
        port: 1433
        max_memory: 2048MB
    firebird:
      category: databases
      version: 3.0
      enabled: false
      config:
        port: 3050
    rethinkdb:
      category: databases
      version: 2.4
      enabled: false
      config:
        port: 28015
        http_port: 8080
  messaging:
    kafka:
      category: messaging
      version: 3.0
      enabled: false
      config:
        port: 9092
        num_partitions: 3
        replication_factor: 1
    rabbitmq:
      category: messaging
      version: 3.9
      enabled: false
      config:
        port: 5672
        management_port: 15672
  coordination:
    zookeeper:
      category: coordination
      version: 3.7
      enabled: false
      config:
        port: 2181
        client_port: 2181
    hazelcast:
      category: coordination
      version: 5.1
      enabled: false
      config:
        port: 5701
        cluster_name: dev-cluster
  monitoring:
    elasticsearch:
      category: monitoring
      version: 7.17
      enabled: false
      config:
        port: 9200
        memory: 512m
        discovery_type: single-node
    prometheus:
      category: monitoring
      version: 2.36
      enabled: false
      config:
        port: 9090
        retention_time: 15d
    grafana:
      category: monitoring
      version: 8.5
      enabled: false
      config:
        port: 3000
        admin_user: admin
  caching:
    memcached:
      category: caching
      version: 1.6
      enabled: false
      config:
        port: 11211
        memory_limit: 64mb
    redis:
      category: caching
      version: 6.2
      enabled: true
      config:
        port: 6379
        maxmemory: 256mb
        maxmemory_policy: allkeys-lru
        password: development
    test-redis:
      category: caching
      version: latest
      enabled: false
      config:
