services:
  caching:
    redis:
      category: caching
      version: 7.0
      enabled: true
      config:
        active_defrag: false
        active_defrag_threshold_lower: 10
        active_defrag_threshold_upper: 100
        appendfsync: everysec
        appendonly: true
        client_output_buffer_limit_normal: "0 0 0"
        client_output_buffer_limit_pubsub: "32mb 8mb 60"
        databases: 16
        latency_monitor_threshold: 100
        lazyfree_lazy_eviction: true
        lazyfree_lazy_expire: true
        maxmemory: 256mb
        maxmemory_policy: allkeys-lru
        maxmemory_samples: 5
        notify_keyspace_events: Kgx
        password: development
        port: 6379
        replica_read_only: true
        save_intervals: "900:1 300:10 60:10000"
        slowlog_log_slower_than: 10000
        slowlog_max_len: 128
        tcp_keepalive: 300
        timeout: 0
    test-redis:
      category: caching
      version: 7.0
      enabled: true
      config:
        appendfsync: always
        appendonly: true
        databases: 8
        maxmemory: 128mb
        maxmemory_policy: volatile-lru
        maxmemory_samples: 10
        notify_keyspace_events: AKE
        port: 6380
        save_intervals: "300:1 60:10 10:100"
        slowlog_log_slower_than: 5000
        slowlog_max_len: 256
  coordination:
    zookeeper:
      category: coordination
      version: 3.9
      enabled: false
      config:
        4lw_commands: mntr,conf,ruok,stat,envi
        autopurge_purge_interval: 24
        autopurge_snap_retain_count: 3
        client_port: 2181
        global_outstanding_limit: 1000
        heap_size: 1G
        init_limit: 10
        jmx_port: 9998
        leader_port: 3888
        max_client_connections: 60
        max_session_timeout: 40000
        min_session_timeout: 4000
        peer_port: 2888
        port: 2181
        sync_limit: 5
        tick_time: 2000
  databases:
    firebird:
      category: databases
      version: 4.0
      enabled: false
      config:
        architecture: superclassic
        connection_timeout: 180
        default_character_set: UTF8
        dummy_packet_interval: 60
        guard_file: guardian
        linger: 30
        max_connections: 100
        page_size: 16384
        port: 3050
        remote_buffer_size: 8K
        security_database: security4.fdb
        temp_cache_limit: 64M
        temp_directories: /tmp
        wire_compression: true
        wire_encryption: false
    mariadb:
      category: databases
      version: 10.11
      enabled: false
      config:
        binlog_expire_logs_seconds: 604800
        character_set_server: utf8mb4
        collation_server: utf8mb4_unicode_ci
        general_log: true
        innodb_buffer_pool_size: 256M
        innodb_log_file_size: 64M
        key_buffer_size: 32M
        long_query_time: 2
        max_allowed_packet: 64M
        max_connections: 100
        port: 3306
        query_cache_size: 32M
        slow_query_log: true
        thread_cache_size: 8
    mongodb:
      category: databases
      version: 6.0
      enabled: false
      config:
        auth_enabled: true
        journal_enabled: true
        max_connections: 100
        oplog_size: 1024
        port: 27017
        profiling_level: 0
        profiling_slow_ms: 100
        replication_enabled: false
        storage_engine: wiredTiger
        wired_tiger_cache_size: 256MB
    mssql:
      category: databases
      version: 2022
      enabled: false
      config:
        allow_snapshot_isolation: true
        clr_enabled: false
        cost_threshold_for_parallelism: 50
        filestream_access_level: 0
        max_degree_of_parallelism: 2
        max_memory: 2048MB
        max_server_memory: 2048
        max_worker_threads: 0
        memory_limit: 2GB
        min_server_memory: 1024
        optimize_for_ad_hoc_workloads: true
        port: 1433
        query_governor_cost_limit: 0
        read_committed_snapshot: true
        remote_query_timeout: 600
        tempdb_file_growth: 128MB
        tempdb_file_size: 512MB
        tempdb_files: 4
    mysql:
      category: databases
      version: 8.0
      enabled: false
      config:
        character_set_server: utf8mb4
        collation_server: utf8mb4_unicode_ci
        default_authentication_plugin: mysql_native_password
        innodb_buffer_pool_size: 128M
        innodb_log_file_size: 64M
        key_buffer_size: 32M
        max_allowed_packet: 64M
        max_connections: 100
        port: 3306
        query_cache_size: 32M
        thread_cache_size: 8
    postgres:
      category: databases
      version: 14
      enabled: false
      config:
        effective_cache_size: 4GB
        maintenance_work_mem: 64MB
        max_connections: 100
        port: 5432
        shared_buffers: 256MB
        timezone: UTC
        work_mem: 4MB
    rethinkdb:
      category: databases
      version: 2.4
      enabled: false
      config:
        bind_cluster: all
        bind_driver: all
        bind_http: all
        cache_size: 1024
        cluster_port: 29015
        cors_allowed_origins: all
        direct_io: true
        directory: /data
        driver_port: 28015
        http_port: 8080
        initial_password: ""
        io_threads: 64
        join: ""
        log_level: info
        no_http_admin: false
        port: 28015
        server_name: rethinkdb_dev
  messaging:
    kafka:
      category: messaging
      version: 3.5
      enabled: true
      config:
        advertised_listeners: PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
        auto_create_topics: true
        delete_topic_enable: true
        heap_opts: "-Xmx1G -Xms1G"
        internal_port: 9093
        jmx_port: 9999
        listeners: PLAINTEXT://:9092,INTERNAL://:9093
        log_retention_bytes: 1073741824
        log_retention_hours: 168
        min_insync_replicas: 1
        num_partitions: 3
        port: 9092
        replication_factor: 1
        zookeeper_connection: zookeeper:2181
    rabbitmq:
      category: messaging
      version: 3.12
      enabled: false
      config:
        amqp_port: 5672
        channel_max: 2047
        cluster_partition_handling: ignore
        collect_statistics: none
        collect_statistics_interval: 5000
        default_permissions: .*
        default_user: guest
        default_vhost: /
        disk_free_limit: 2GB
        heartbeat: 60
        management_db_cache_multiplier: 5
        management_port: 15672
        memory_high_watermark: 0.4
        mqtt_port: 1883
        port: 5672
        stomp_port: 61613
        vm_memory_high_watermark_paging_ratio: 0.5
