services:
  databases:
    postgres:
      enabled: true
      version: "14"
      config:
        port: 5432
        max_connections: 100
        shared_buffers: "256MB"
        
    mysql:
      enabled: false
      version: "8.0"
      config:
        port: 3306
        max_connections: 100
        
    mongodb:
      enabled: false
      version: "5.0"
      config:
        port: 27017
        storage_engine: "wiredTiger"
        
    redis:
      enabled: true
      version: "6.2"
      config:
        port: 6379
        maxmemory: "256mb"
        maxmemory_policy: "allkeys-lru"

  messaging:
    kafka:
      enabled: false
      version: "3.0"
      config:
        port: 9092
        num_partitions: 3
        replication_factor: 1
        
    rabbitmq:
      enabled: false
      version: "3.9"
      config:
        port: 5672
        management_port: 15672
        
  caching:
    hazelcast:
      enabled: false
      version: "5.1"
      config:
        port: 5701
        cluster_name: "dev-cluster"
        
    memcached:
      enabled: false
      version: "1.6"
      config:
        port: 11211
        memory_limit: "64mb"

  search:
    elasticsearch:
      enabled: false
      version: "7.17"
      config:
        port: 9200
        memory: "512m"
        discovery_type: "single-node"

  monitoring:
    prometheus:
      enabled: false
      version: "2.36"
      config:
        port: 9090
        retention_time: "15d"
        
    grafana:
      enabled: false
      version: "8.5"
      config:
        port: 3000
        admin_user: "admin"
