services:

  redis:
    build:
      context: ./services/caching/redis
      args:
        VERSION: 6.2
    container_name: redis
    restart: unless-stopped
    environment:
      - REDIS_DATABASES
      - REDIS_MAX_MEMORY
      - REDIS_MAX_MEMORY_POLICY
      - REDIS_MAX_MEMORY_SAMPLES
      - REDIS_ACTIVE_DEFRAG
      - REDIS_APPEND_ONLY
      - REDIS_SAVE_INTERVALS
      - REDIS_NOTIFY_KEYSPACE_EVENTS
      - REDIS_SLOWLOG_LOG_SLOWER_THAN
      - REDIS_SLOWLOG_MAX_LEN
      - REDIS_LATENCY_MONITOR_THRESHOLD
      - REDIS_LAZYFREE_LAZY_EVICTION
      - REDIS_LAZYFREE_LAZY_EXPIRE
      - TZ
      - REDIS_PASSWORD=development
    volumes:
      - data:/data
      - backups:/backups
      - logs:/var/log/redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - dev_network
    # Service-specific configuration
    # maxmemory: 256mb
    # maxmemory_policy: allkeys-lru
    # password: development

networks:
  dev_network:
    driver: bridge

volumes:
  data:
    driver: local
  backups:
    driver: local
  logs:
    driver: local
