name: platform_broadcasting
description: The Broadcasting Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

dependencies:
  crypto: ^3.0.3
  http: ^1.2.0
  meta: ^1.12.0
  pusher_client: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
