name: pdo
description: A Dart implementation of PHP's PDO (PHP Data Objects) database abstraction layer.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

# Expose test_helpers directory for use in tests and examples
false_secrets:
  - /lib/src/test_helpers/test_utils.dart
