name: Application
class_comment: null
dependencies: []
properties: []
methods:
- name: call
  visibility: public
  parameters:
  - name: command
  - name: parameters
    default: '[]'
  - name: outputBuffer
    default: 'null'
  comment: '# * Run an Artisan console command by name.

    # *

    # * @param  string  $command

    # * @param  array  $parameters

    # * @param  \Symfony\Component\Console\Output\OutputInterface|null  $outputBuffer

    # * @return int'
- name: output
  visibility: public
  parameters: []
  comment: '# * Get the output from the last command.

    # *

    # * @return string'
traits: []
interfaces: []
