name: mariadb
category: databases
description: MariaDB database server
versions:
  - "10.11"
  - "10.10"
  - "10.9"
default_version: "10.11"

config_schema:
  port:
    type: integer
    default: 3306
    description: Port to expose MariaDB
    required: true

  max_connections:
    type: integer
    default: 100
    description: Maximum number of concurrent connections
    required: false

  innodb_buffer_pool_size:
    type: string
    default: "256M"
    description: Size of InnoDB buffer pool
    required: false

  innodb_log_file_size:
    type: string
    default: "64M"
    description: Size of InnoDB log files
    required: false

  max_allowed_packet:
    type: string
    default: "64M"
    description: Maximum size of one packet
    required: false

  key_buffer_size:
    type: string
    default: "32M"
    description: Size of buffer used for MyISAM table indexes
    required: false

  thread_cache_size:
    type: integer
    default: 8
    description: Number of threads to cache
    required: false

  query_cache_size:
    type: string
    default: "32M"
    description: Size of query cache
    required: false

  character_set_server:
    type: string
    default: "utf8mb4"
    description: Default character set
    required: false

  collation_server:
    type: string
    default: "utf8mb4_unicode_ci"
    description: Default collation
    required: false

  slow_query_log:
    type: boolean
    default: true
    description: Enable slow query logging
    required: false

  long_query_time:
    type: integer
    default: 2
    description: Time in seconds to log slow queries
    required: false

  general_log:
    type: boolean
    default: true
    description: Enable general query logging for development
    required: false

  binlog_expire_logs_seconds:
    type: integer
    default: 604800
    description: Binary log expiration in seconds
    required: false

volumes:
  - data:/var/lib/mysql
  - backups:/backups
  - logs:/var/log/mysql

environment:
  - MARIADB_ROOT_PASSWORD
  - MARIADB_DATABASE
  - MARIADB_USER
  - MARIADB_PASSWORD
  - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
  - MARIADB_RANDOM_ROOT_PASSWORD
  - MARIADB_INITDB_SKIP_TZINFO
  - MARIADB_ROOT_HOST
  - DEV_DB_NAME
  - DEV_DB_USER
  - DEV_DB_PASSWORD
  - CREATE_TEST_DB
  - TZ

health_check:
  command: "mysqladmin ping -h localhost -u root --password=\"${MARIADB_ROOT_PASSWORD}\""
  interval: "10s"
  timeout: "5s"
  retries: 3
  start_period: "30s"

ports:
  - 3306  # Main port
  - 33060 # X Protocol port (if enabled)
