name: dsr_http_factory
description: A PSR-17 compatible HTTP factory interface for Dart. Provides standardized interfaces for creating PSR-7 HTTP message objects including requests, responses, streams, and URIs.
version: 0.0.1
homepage: https://dart-fig.org

environment:
  sdk: ^3.4.2

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
