name: platform_seo
version: 8.2.0
description: Helper infrastructure for building SEO-friendly Web backends in Platform.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/angel3/packages/seo
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  platform_foundation: ^8.0.0
  platform_static: ^8.0.0
  file: ^7.0.0
  html: ^0.15.0
  http_parser: ^4.0.0
  path: ^1.9.0
dev_dependencies:
  platform_testing: ^8.0.0
  logging: ^1.2.0
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   angel3_static:
#     path: ../static
#   angel3_websocket:
#     path: ../websocket
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth 
#   angel3_client:
#     path: ../client
#   angel3_test:
#     path: ../test
#   angel3_validate:
#     path: ../validate