name: illuminate_view
description: A flexible and powerful templating system for Dart, inspired by Laravel's View system. Provides template rendering, multiple engine support, shared data, namespaced views, and an extensible architecture.
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

dependencies:
  path: ^1.8.0
  meta: ^1.9.0
  collection: ^1.18.0
  illuminate_contracts: ^0.5.1
  illuminate_events: ^0.5.1
  illuminate_support: ^0.5.1
  illuminate_translation: ^0.5.1
  illuminate_container: ^0.5.1
  illuminate_filesystem: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

topics:
  - templates
  - views
  - rendering
  - laravel
