name: view
description: View rendering package implementing Laravel-style view system
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.0
  meta: ^1.9.0
  collection: ^1.18.0
  mustache_template: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
