name: events_example
description: Example for the platform_events package
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  platform_events:
    path: ../
  platform_container:
    path: ../../container/container

dev_dependencies:
  lints: ^2.0.0
