name: events_example
description: Example for the platform_events package
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  illuminate_events: ^0.5.1
  illuminate_container: ^0.5.1
  illuminate_contracts: ^0.5.1

dev_dependencies:
  lints: ^2.0.0
  coverage: ^1.11.1
