name: illuminate_mirrors
description: A runtime reflection system for Dart that provides introspection capabilities.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  meta: ^1.9.0
  path: ^1.9.1
  illuminate_contracts: ^0.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0

publish_to: none
