name: platform_mirrors
description: A lightweight, cross-platform reflection system for Dart
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  platform_contracts: ^0.1.0
  meta: ^1.9.0
  collection: ^1.17.0

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  lints: ^2.1.0
