name: MainConfiguration
class_comment: '# * SecurityExtension configuration structure.

  # *

  # * @author Johannes M. Schmitt <schmittjoh@gmail.com>'
dependencies:
- name: AbstractFactory
  type: class
  source: Symfony\Bundle\SecurityBundle\DependencyInjection\Security\Factory\AbstractFactory
- name: AuthenticatorFactoryInterface
  type: class
  source: Symfony\Bundle\SecurityBundle\DependencyInjection\Security\Factory\AuthenticatorFactoryInterface
- name: ArrayNodeDefinition
  type: class
  source: Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition
- name: TreeBuilder
  type: class
  source: Symfony\Component\Config\Definition\Builder\TreeBuilder
- name: ConfigurationInterface
  type: class
  source: Symfony\Component\Config\Definition\ConfigurationInterface
- name: InvalidConfigurationException
  type: class
  source: Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
- name: AuthenticationEntryPointInterface
  type: class
  source: Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface
- name: SessionAuthenticationStrategy
  type: class
  source: Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: factories
  - name: userProviderFactories
  comment: "# * SecurityExtension configuration structure.\n# *\n# * @author Johannes\
    \ M. Schmitt <schmittjoh@gmail.com>\n# */\n# class MainConfiguration implements\
    \ ConfigurationInterface\n# {\n# /** @internal */\n# public const STRATEGY_AFFIRMATIVE\
    \ = 'affirmative';\n# /** @internal */\n# public const STRATEGY_CONSENSUS = 'consensus';\n\
    # /** @internal */\n# public const STRATEGY_UNANIMOUS = 'unanimous';\n# /** @internal\
    \ */\n# public const STRATEGY_PRIORITY = 'priority';\n# \n# /**\n# * @param array<AuthenticatorFactoryInterface>\
    \ $factories"
- name: getConfigTreeBuilder
  visibility: public
  parameters: []
  comment: '# * Generates the configuration tree builder.'
- name: addRoleHierarchySection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addAccessControlSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addFirewallsSection
  visibility: private
  parameters:
  - name: rootNode
  - name: factories
  comment: '# * @param array<AuthenticatorFactoryInterface> $factories'
- name: addProvidersSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addPasswordHashersSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: getAccessDecisionStrategies
  visibility: private
  parameters: []
  comment: null
traits:
- Symfony\Bundle\SecurityBundle\DependencyInjection\Security\Factory\AbstractFactory
- Symfony\Bundle\SecurityBundle\DependencyInjection\Security\Factory\AuthenticatorFactoryInterface
- Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition
- Symfony\Component\Config\Definition\Builder\TreeBuilder
- Symfony\Component\Config\Definition\ConfigurationInterface
- Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
- Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface
- Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy
interfaces:
- ConfigurationInterface
