name: protevus_auth
description: The Authentication Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  protevus_http: ^0.0.1
  protevus_openapi: ^0.0.1
  protevus_hashing: ^0.0.1
  crypto: ^3.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
