name: illuminate_auth
description: Authentication package for protevus platform with jsonwebtoken(jwt) driver.
version: 2.0.0
repository: https://github.com/dartondox/dox

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.8.2
  illuminate_contracts: ^0.0.1
  illuminate_database: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
