name: protevus_platform
repository: https://github.com/protevus/platform
packages:
  - fig/**
  - common/**
  - drivers/**
  - packages/**
  - incubation/**
  - apps/**
  - helpers/tools/**
  - examples/**

command:
  version:
    linkToCommits: true
    message: "chore: Bump version to %v"
    branch: main
    workspaceChangelog: true
    
ide:
  intellij:
    enabled: false

scripts:
  _: &base_scripts
    
