name: ConfigBuilderCacheWarmer
class_comment: '# * Generate all config builders.

  # *

  # * @author Tobias Nyholm <tobias.nyholm@gmail.com>

  # *

  # * @final since Symfony 7.1'
dependencies:
- name: LoggerInterface
  type: class
  source: Psr\Log\LoggerInterface
- name: ConfigBuilderGenerator
  type: class
  source: Symfony\Component\Config\Builder\ConfigBuilderGenerator
- name: ConfigBuilderGeneratorInterface
  type: class
  source: Symfony\Component\Config\Builder\ConfigBuilderGeneratorInterface
- name: ConfigurationInterface
  type: class
  source: Symfony\Component\Config\Definition\ConfigurationInterface
- name: Container
  type: class
  source: Symfony\Component\DependencyInjection\Container
- name: ContainerBuilder
  type: class
  source: Symfony\Component\DependencyInjection\ContainerBuilder
- name: ConfigurationExtensionInterface
  type: class
  source: Symfony\Component\DependencyInjection\Extension\ConfigurationExtensionInterface
- name: ExtensionInterface
  type: class
  source: Symfony\Component\DependencyInjection\Extension\ExtensionInterface
- name: ContainerBag
  type: class
  source: Symfony\Component\DependencyInjection\ParameterBag\ContainerBag
- name: ParameterBag
  type: class
  source: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
- name: CacheWarmerInterface
  type: class
  source: Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface
- name: Kernel
  type: class
  source: Symfony\Component\HttpKernel\Kernel
- name: KernelInterface
  type: class
  source: Symfony\Component\HttpKernel\KernelInterface
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: kernel
  - name: logger
    default: 'null'
  comment: null
- name: warmUp
  visibility: public
  parameters:
  - name: cacheDir
  - name: buildDir
    default: 'null'
  comment: null
- name: dumpExtension
  visibility: private
  parameters:
  - name: extension
  - name: generator
  comment: null
- name: isOptional
  visibility: public
  parameters: []
  comment: null
traits:
- Psr\Log\LoggerInterface
- Symfony\Component\Config\Builder\ConfigBuilderGenerator
- Symfony\Component\Config\Builder\ConfigBuilderGeneratorInterface
- Symfony\Component\Config\Definition\ConfigurationInterface
- Symfony\Component\DependencyInjection\Container
- Symfony\Component\DependencyInjection\ContainerBuilder
- Symfony\Component\DependencyInjection\Extension\ConfigurationExtensionInterface
- Symfony\Component\DependencyInjection\Extension\ExtensionInterface
- Symfony\Component\DependencyInjection\ParameterBag\ContainerBag
- Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
- Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface
- Symfony\Component\HttpKernel\Kernel
- Symfony\Component\HttpKernel\KernelInterface
interfaces:
- CacheWarmerInterface
