name: platform_mocking
version: 9.0.0
description: Protevus Platform Mocking for dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/mocking
environment:
    sdk: '>=3.3.0 <4.0.0'
dependencies:
  charcode: ^1.3.1
dev_dependencies:
  http: ^1.2.2
  test: ^1.25.8
  lints: ^4.0.0
# dependency_overrides:
#   platform_core:
#     path: ../framework
#   platform_route:
#     path: ../route
#   platform_model:
#     path: ../model
#   platform_exceptions:
#     path: ../exceptions
#   platform_container:
#     path: ../container/container