name: Configuration
class_comment: '# * TwigExtension configuration structure.

  # *

  # * @author Jeremy Mikola <jmikola@gmail.com>'
dependencies:
- name: ArrayNodeDefinition
  type: class
  source: Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition
- name: TreeBuilder
  type: class
  source: Symfony\Component\Config\Definition\Builder\TreeBuilder
- name: ConfigurationInterface
  type: class
  source: Symfony\Component\Config\Definition\ConfigurationInterface
- name: InvalidConfigurationException
  type: class
  source: Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
- name: HtmlToTextConverterInterface
  type: class
  source: Symfony\Component\Mime\HtmlToTextConverter\HtmlToTextConverterInterface
properties: []
methods:
- name: getConfigTreeBuilder
  visibility: public
  parameters: []
  comment: '# * TwigExtension configuration structure.

    # *

    # * @author Jeremy Mikola <jmikola@gmail.com>

    # */

    # class Configuration implements ConfigurationInterface

    # {

    # /**

    # * Generates the configuration tree builder.'
- name: addFormThemesSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addGlobalsSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addTwigOptions
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addTwigFormatOptions
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addMailerSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
traits:
- Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition
- Symfony\Component\Config\Definition\Builder\TreeBuilder
- Symfony\Component\Config\Definition\ConfigurationInterface
- Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
- Symfony\Component\Mime\HtmlToTextConverter\HtmlToTextConverterInterface
interfaces:
- ConfigurationInterface
