name: illuminate_session
description: The Session Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

dependencies:
  illuminate_foundation: ^0.0.1
  illuminate_encryption: ^0.0.1
  illuminate_cache: ^0.0.1
  illuminate_contracts: ^0.0.1
  illuminate_http: ^0.0.1
  illuminate_support: ^0.0.1
  illuminate_container: ^0.0.1
  illuminate_database: ^0.0.1
  #illuminate_redis: ^0.0.1
  illuminate_dbo: ^0.0.1
  crypto: ^3.0.3
  logging: ^1.2.0
  meta: ^1.11.0
  path: ^1.8.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
