name: "test-redis"
category: "caching"
versions:
  - "latest"
default_version: "latest"
config_schema: {}
volumes: []
environment: []
health_check:
  command: "exit 0"
  interval: "30s"
  timeout: "5s"
  retries: 3
