name: "❓ Question or Support Request"
description: "Questions and requests for support."
title: "[Question]"
labels: ["Type: Question"]

body:
  - type: markdown
    attributes:
      value: |
        # **❓ Question or Support Request**

        Please describe your question or ask for support below.

  - type: textarea
    id: question-or-support
    attributes:
      label: Describe your question or ask for support
      description: A clear and concise description of what your doubt is.
      placeholder: Provide a detailed description of your question or the support you need.

  - type: markdown
    attributes:
      value: |
        <!--📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛

        Oh, hi there! 😄

        Before posting any questions or asking for support, first read the project's README.md file and
        (if there is any) the WIKI pages or any other additional documentation that might be listed
        in the project's README.md file.

        To expedite issue processing, please search open and closed issues before submitting a new one.
        Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`

        📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛📛-->
