blank_issues_enabled: false
contact_links:
    - name: Send an e-mail to the developer
      url: mailto:jgracia9988@gmail.com
      about: Please do NOT use this email to post issues or feature requests (only important business/personal contact).
    - name: Bug Report
      url: https://github.com/protevus/platform/issues/new?template=1-bug-report.yml
