name: Values
class_comment: '# * @author Nicolas Grekas <p@tchwork.com>

  # *

  # * @internal'
dependencies: []
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: values
  comment: null
traits: []
interfaces: []
