name: platform_oauth2
version: 8.2.0
description: A class containing handlers that can be used within Angel to build a spec-compliant OAuth 2.0 server.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/oauth2
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies: 
  platform_foundation: ^8.0.0
  platform_support: ^8.0.0
  crypto: ^3.0.1
  collection: ^1.17.0
  logging: ^1.2.0
dev_dependencies: 
  platform_validation: ^8.0.0
  platform_testing: ^8.0.0
  platform_container: ^8.0.0
  oauth2: ^2.0.0
  lints: ^4.0.0
  test: ^1.24.0
  uuid: ^4.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_test:
#     path: ../test
#   angel3_validate:
#     path: ../validate
#   angel3_websocket:
#     path: ../websocket
#   angel3_client:
#     path: ../client
#   angel3_auth:
#     path: ../auth