name: dsr_http_client
description: A PSR-18 compatible HTTP client interface for Dart. Provides standardized interfaces for sending HTTP requests including ClientInterface and related exceptions.
version: 0.0.1
homepage: https://dart-fig.org

environment:
  sdk: ^3.4.2

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
