name: illuminate_process
description: A Laravel-compatible process management implementation in pure Dart
version: 1.0.0
homepage: https://github.com/platform/platform_process

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.9.1
  path: ^1.8.0
  async: ^2.11.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
