name: platform_collections
description: A Dart implementation of Laravel's Collection class, providing fluent wrappers for working with arrays of data
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.0
  platform_contracts: ^0.1.0
  platform_mirrors: ^0.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
