name: platform_collections
description: A Dart implementation of Laravel-inspired collections.
version: 1.0.0
homepage: https://github.com/yourusername/collections

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: {}

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
