name: AbstractServiceConfigurator
class_comment: null
dependencies:
- name: Definition
  type: class
  source: Symfony\Component\DependencyInjection\Definition
- name: ServiceNotFoundException
  type: class
  source: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: parent
  - name: definition
  - name: id
    default: 'null'
  - name: defaultTags
    default: '[]'
  comment: null
- name: __destruct
  visibility: public
  parameters: []
  comment: null
- name: set
  visibility: public
  parameters:
  - name: id
  - name: class
    default: 'null'
  comment: null
- name: alias
  visibility: public
  parameters:
  - name: id
  - name: referencedId
  comment: null
- name: load
  visibility: public
  parameters:
  - name: namespace
  - name: resource
  comment: null
- name: get
  visibility: public
  parameters:
  - name: id
  comment: null
- name: remove
  visibility: public
  parameters:
  - name: id
  comment: null
- name: stack
  visibility: public
  parameters:
  - name: id
  - name: services
  comment: null
- name: __invoke
  visibility: public
  parameters:
  - name: id
  - name: class
    default: 'null'
  comment: null
traits:
- Symfony\Component\DependencyInjection\Definition
- Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException
interfaces: []
