name: AliasConfigurator
class_comment: '# * @author Nicolas Grekas <p@tchwork.com>'
dependencies:
- name: Alias
  type: class
  source: Symfony\Component\DependencyInjection\Alias
- name: DeprecateTrait
  type: class
  source: Traits\DeprecateTrait
- name: PublicTrait
  type: class
  source: Traits\PublicTrait
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: parent
  - name: alias
  comment: null
traits:
- Symfony\Component\DependencyInjection\Alias
- Traits\DeprecateTrait
- Traits\PublicTrait
interfaces: []
