name: DefaultsConfigurator
class_comment: '# * @author Nicolas Grekas <p@tchwork.com>'
dependencies:
- name: Definition
  type: class
  source: Symfony\Component\DependencyInjection\Definition
- name: InvalidArgumentException
  type: class
  source: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
- name: AutoconfigureTrait
  type: class
  source: Traits\AutoconfigureTrait
- name: AutowireTrait
  type: class
  source: Traits\AutowireTrait
- name: BindTrait
  type: class
  source: Traits\BindTrait
- name: PublicTrait
  type: class
  source: Traits\PublicTrait
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: parent
  - name: definition
  - name: path
    default: 'null'
  comment: null
- name: tag
  visibility: public
  parameters:
  - name: name
  - name: attributes
    default: '[]'
  comment: null
- name: instanceof
  visibility: public
  parameters:
  - name: fqcn
  comment: null
- name: validateAttributes
  visibility: private
  parameters:
  - name: tag
  - name: attributes
  - name: path
    default: '[]'
  comment: null
traits:
- Symfony\Component\DependencyInjection\Definition
- Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
- Traits\AutoconfigureTrait
- Traits\AutowireTrait
- Traits\BindTrait
- Traits\PublicTrait
interfaces: []
