name: InstanceofConfigurator
class_comment: '# * @author Nicolas Grekas <p@tchwork.com>'
dependencies:
- name: Definition
  type: class
  source: Symfony\Component\DependencyInjection\Definition
- name: AutowireTrait
  type: class
  source: Traits\AutowireTrait
- name: BindTrait
  type: class
  source: Traits\BindTrait
- name: CallTrait
  type: class
  source: Traits\CallTrait
- name: ConfiguratorTrait
  type: class
  source: Traits\ConfiguratorTrait
- name: ConstructorTrait
  type: class
  source: Traits\ConstructorTrait
- name: LazyTrait
  type: class
  source: Traits\LazyTrait
- name: PropertyTrait
  type: class
  source: Traits\PropertyTrait
- name: PublicTrait
  type: class
  source: Traits\PublicTrait
- name: ShareTrait
  type: class
  source: Traits\ShareTrait
- name: TagTrait
  type: class
  source: Traits\TagTrait
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: parent
  - name: definition
  - name: id
  - name: path
    default: 'null'
  comment: null
- name: instanceof
  visibility: public
  parameters:
  - name: fqcn
  comment: null
traits:
- Symfony\Component\DependencyInjection\Definition
- Traits\AutowireTrait
- Traits\BindTrait
- Traits\CallTrait
- Traits\ConfiguratorTrait
- Traits\ConstructorTrait
- Traits\LazyTrait
- Traits\PropertyTrait
- Traits\PublicTrait
- Traits\ShareTrait
- Traits\TagTrait
interfaces: []
