name: ReferenceConfigurator
class_comment: '# * @author Nicolas Grekas <p@tchwork.com>'
dependencies:
- name: ContainerInterface
  type: class
  source: Symfony\Component\DependencyInjection\ContainerInterface
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: id
  comment: null
- name: ignoreOnInvalid
  visibility: public
  parameters: []
  comment: null
- name: nullOnInvalid
  visibility: public
  parameters: []
  comment: null
- name: ignoreOnUninitialized
  visibility: public
  parameters: []
  comment: null
- name: __toString
  visibility: public
  parameters: []
  comment: null
traits:
- Symfony\Component\DependencyInjection\ContainerInterface
interfaces: []
