name: ServicesConfigurator
class_comment: '# * @author Nicolas Grekas <p@tchwork.com>'
dependencies:
- name: Alias
  type: class
  source: Symfony\Component\DependencyInjection\Alias
- name: ChildDefinition
  type: class
  source: Symfony\Component\DependencyInjection\ChildDefinition
- name: ContainerBuilder
  type: class
  source: Symfony\Component\DependencyInjection\ContainerBuilder
- name: Definition
  type: class
  source: Symfony\Component\DependencyInjection\Definition
- name: InvalidArgumentException
  type: class
  source: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
- name: ServiceNotFoundException
  type: class
  source: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException
- name: PhpFileLoader
  type: class
  source: Symfony\Component\DependencyInjection\Loader\PhpFileLoader
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: container
  - name: loader
  - name: '&$instanceof'
  - name: path
    default: 'null'
  - name: '&$anonymousCount'
    default: '0'
  comment: null
- name: defaults
  visibility: public
  parameters: []
  comment: null
- name: instanceof
  visibility: public
  parameters:
  - name: fqcn
  comment: null
- name: set
  visibility: public
  parameters:
  - name: id
  - name: class
    default: 'null'
  comment: null
- name: remove
  visibility: public
  parameters:
  - name: id
  comment: null
- name: alias
  visibility: public
  parameters:
  - name: id
  - name: referencedId
  comment: null
- name: load
  visibility: public
  parameters:
  - name: namespace
  - name: resource
  comment: null
- name: get
  visibility: public
  parameters:
  - name: id
  comment: null
- name: stack
  visibility: public
  parameters:
  - name: id
  - name: services
  comment: null
- name: __invoke
  visibility: public
  parameters:
  - name: id
  - name: class
    default: 'null'
  comment: null
- name: __destruct
  visibility: public
  parameters: []
  comment: null
traits:
- Symfony\Component\DependencyInjection\Alias
- Symfony\Component\DependencyInjection\ChildDefinition
- Symfony\Component\DependencyInjection\ContainerBuilder
- Symfony\Component\DependencyInjection\Definition
- Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
- Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException
- Symfony\Component\DependencyInjection\Loader\PhpFileLoader
interfaces: []
