name: platform_model
version: 9.0.0
description: Protevus Platform basic data model class, no longer with the added weight of the whole framework.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/model
environment:
  sdk: '>=3.3.0 <4.0.0'
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
