name: RegisterAutoconfigureAttributesPass
class_comment: null
dependencies:
- name: Autoconfigure
  type: class
  source: Symfony\Component\DependencyInjection\Attribute\Autoconfigure
- name: Lazy
  type: class
  source: Symfony\Component\DependencyInjection\Attribute\Lazy
- name: ContainerBuilder
  type: class
  source: Symfony\Component\DependencyInjection\ContainerBuilder
- name: Definition
  type: class
  source: Symfony\Component\DependencyInjection\Definition
- name: AutoconfigureFailedException
  type: class
  source: Symfony\Component\DependencyInjection\Exception\AutoconfigureFailedException
- name: YamlFileLoader
  type: class
  source: Symfony\Component\DependencyInjection\Loader\YamlFileLoader
properties: []
methods:
- name: process
  visibility: public
  parameters:
  - name: container
  comment: null
- name: accept
  visibility: public
  parameters:
  - name: definition
  comment: null
- name: processClass
  visibility: public
  parameters:
  - name: container
  - name: class
  comment: null
- name: registerForAutoconfiguration
  visibility: private
  parameters:
  - name: container
  - name: class
  - name: attribute
  comment: null
traits:
- Symfony\Component\DependencyInjection\Attribute\Autoconfigure
- Symfony\Component\DependencyInjection\Attribute\Lazy
- Symfony\Component\DependencyInjection\ContainerBuilder
- Symfony\Component\DependencyInjection\Definition
- Symfony\Component\DependencyInjection\Exception\AutoconfigureFailedException
- Symfony\Component\DependencyInjection\Loader\YamlFileLoader
interfaces:
- CompilerPassInterface
