name: Configuration
class_comment: '# * FrameworkExtension configuration structure.'
dependencies:
- name: Connection
  type: class
  source: Doctrine\DBAL\Connection
- name: LogLevel
  type: class
  source: Psr\Log\LogLevel
- name: JsonParser
  type: class
  source: Seld\JsonLint\JsonParser
- name: FullStack
  type: class
  source: Symfony\Bundle\FullStack
- name: Package
  type: class
  source: Symfony\Component\Asset\Package
- name: AssetMapper
  type: class
  source: Symfony\Component\AssetMapper\AssetMapper
- name: DoctrineAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\DoctrineAdapter
- name: ArrayNodeDefinition
  type: class
  source: Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition
- name: NodeBuilder
  type: class
  source: Symfony\Component\Config\Definition\Builder\NodeBuilder
- name: TreeBuilder
  type: class
  source: Symfony\Component\Config\Definition\Builder\TreeBuilder
- name: ConfigurationInterface
  type: class
  source: Symfony\Component\Config\Definition\ConfigurationInterface
- name: InvalidConfigurationException
  type: class
  source: Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
- name: ContainerBuilder
  type: class
  source: Symfony\Component\DependencyInjection\ContainerBuilder
- name: LogicException
  type: class
  source: Symfony\Component\DependencyInjection\Exception\LogicException
- name: Form
  type: class
  source: Symfony\Component\Form\Form
- name: HtmlSanitizerInterface
  type: class
  source: Symfony\Component\HtmlSanitizer\HtmlSanitizerInterface
- name: HttpClient
  type: class
  source: Symfony\Component\HttpClient\HttpClient
- name: Cookie
  type: class
  source: Symfony\Component\HttpFoundation\Cookie
- name: IpUtils
  type: class
  source: Symfony\Component\HttpFoundation\IpUtils
- name: Lock
  type: class
  source: Symfony\Component\Lock\Lock
- name: SemaphoreStore
  type: class
  source: Symfony\Component\Lock\Store\SemaphoreStore
- name: Mailer
  type: class
  source: Symfony\Component\Mailer\Mailer
- name: MessageBusInterface
  type: class
  source: Symfony\Component\Messenger\MessageBusInterface
- name: Notifier
  type: class
  source: Symfony\Component\Notifier\Notifier
- name: PropertyAccessor
  type: class
  source: Symfony\Component\PropertyAccess\PropertyAccessor
- name: PropertyInfoExtractorInterface
  type: class
  source: Symfony\Component\PropertyInfo\PropertyInfoExtractorInterface
- name: TokenBucketLimiter
  type: class
  source: Symfony\Component\RateLimiter\Policy\TokenBucketLimiter
- name: RemoteEvent
  type: class
  source: Symfony\Component\RemoteEvent\RemoteEvent
- name: Schedule
  type: class
  source: Symfony\Component\Scheduler\Schedule
- name: Semaphore
  type: class
  source: Symfony\Component\Semaphore\Semaphore
- name: JsonDecode
  type: class
  source: Symfony\Component\Serializer\Encoder\JsonDecode
- name: Serializer
  type: class
  source: Symfony\Component\Serializer\Serializer
- name: Translator
  type: class
  source: Symfony\Component\Translation\Translator
- name: Type
  type: class
  source: Symfony\Component\TypeInfo\Type
- name: UuidFactory
  type: class
  source: Symfony\Component\Uid\Factory\UuidFactory
- name: Validation
  type: class
  source: Symfony\Component\Validator\Validation
- name: WebhookController
  type: class
  source: Symfony\Component\Webhook\Controller\WebhookController
- name: HttpHeaderSerializer
  type: class
  source: Symfony\Component\WebLink\HttpHeaderSerializer
- name: WorkflowEvents
  type: class
  source: Symfony\Component\Workflow\WorkflowEvents
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: debug
  comment: '# * FrameworkExtension configuration structure.

    # */

    # class Configuration implements ConfigurationInterface

    # {

    # /**

    # * @param bool $debug Whether debugging is enabled or not'
- name: getConfigTreeBuilder
  visibility: public
  parameters: []
  comment: '# * Generates the configuration tree builder.'
- name: addSecretsSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addCsrfSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addFormSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addHttpCacheSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addEsiSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addSsiSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addFragmentsSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addProfilerSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addWorkflowSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addRouterSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addSessionSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addRequestSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addAssetsSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addAssetMapperSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addTranslatorSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addValidationSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addAnnotationsSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addSerializerSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addPropertyAccessSection
  visibility: private
  parameters:
  - name: rootNode
  - name: willBeAvailable
  comment: null
- name: addPropertyInfoSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addTypeInfoSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addCacheSection
  visibility: private
  parameters:
  - name: rootNode
  - name: willBeAvailable
  comment: null
- name: addPhpErrorsSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addExceptionsSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addLockSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addSemaphoreSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addWebLinkSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addMessengerSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addSchedulerSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addRobotsIndexSection
  visibility: private
  parameters:
  - name: rootNode
  comment: null
- name: addHttpClientSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: createHttpClientRetrySection
  visibility: private
  parameters: []
  comment: null
- name: addMailerSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addNotifierSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addWebhookSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addRemoteEventSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addRateLimiterSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addUidSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
- name: addHtmlSanitizerSection
  visibility: private
  parameters:
  - name: rootNode
  - name: enableIfStandalone
  comment: null
traits:
- Doctrine\DBAL\Connection
- Psr\Log\LogLevel
- Seld\JsonLint\JsonParser
- Symfony\Bundle\FullStack
- Symfony\Component\Asset\Package
- Symfony\Component\AssetMapper\AssetMapper
- Symfony\Component\Cache\Adapter\DoctrineAdapter
- Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition
- Symfony\Component\Config\Definition\Builder\NodeBuilder
- Symfony\Component\Config\Definition\Builder\TreeBuilder
- Symfony\Component\Config\Definition\ConfigurationInterface
- Symfony\Component\Config\Definition\Exception\InvalidConfigurationException
- Symfony\Component\DependencyInjection\ContainerBuilder
- Symfony\Component\DependencyInjection\Exception\LogicException
- Symfony\Component\Form\Form
- Symfony\Component\HtmlSanitizer\HtmlSanitizerInterface
- Symfony\Component\HttpClient\HttpClient
- Symfony\Component\HttpFoundation\Cookie
- Symfony\Component\HttpFoundation\IpUtils
- Symfony\Component\Lock\Lock
- Symfony\Component\Lock\Store\SemaphoreStore
- Symfony\Component\Mailer\Mailer
- Symfony\Component\Messenger\MessageBusInterface
- Symfony\Component\Notifier\Notifier
- Symfony\Component\PropertyAccess\PropertyAccessor
- Symfony\Component\PropertyInfo\PropertyInfoExtractorInterface
- Symfony\Component\RateLimiter\Policy\TokenBucketLimiter
- Symfony\Component\RemoteEvent\RemoteEvent
- Symfony\Component\Scheduler\Schedule
- Symfony\Component\Semaphore\Semaphore
- Symfony\Component\Serializer\Encoder\JsonDecode
- Symfony\Component\Serializer\Serializer
- Symfony\Component\Translation\Translator
- Symfony\Component\TypeInfo\Type
- Symfony\Component\Uid\Factory\UuidFactory
- Symfony\Component\Validator\Validation
- Symfony\Component\Webhook\Controller\WebhookController
- Symfony\Component\WebLink\HttpHeaderSerializer
- Symfony\Component\Workflow\WorkflowEvents
interfaces:
- ConfigurationInterface
