name: platform_mongo
version: 8.2.1
description: This is MongoDB-enabled service for the Platform framework.
homepage: https://platform-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/mongo
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  platform_foundation: ^8.4.0
  platform_container: ^8.2.0
  belatuk_json_serializer: ^7.1.0
  belatuk_merge_map: ^5.1.0
  mongo_dart: ^0.10.3

dev_dependencies:
  http: ^1.0.0
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   platform_container:
#     path: ../container/angel_container
#   platform_framework:
#     path: ../framework
#   platform_http_exception:
#     path: ../http_exception
#   platform_model:
#     path: ../model
#   platform_route:
#     path: ../route
#   platform_mock_request:
#     path: ../mock_request