name: TwigEnvironmentPass
class_comment: '# * Adds tagged twig.extension services to twig service.

  # *

  # * @author Fabien Potencier <fabien@symfony.com>'
dependencies:
- name: CompilerPassInterface
  type: class
  source: Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface
- name: PriorityTaggedServiceTrait
  type: class
  source: Symfony\Component\DependencyInjection\Compiler\PriorityTaggedServiceTrait
- name: ContainerBuilder
  type: class
  source: Symfony\Component\DependencyInjection\ContainerBuilder
- name: PriorityTaggedServiceTrait
  type: class
  source: PriorityTaggedServiceTrait
properties: []
methods:
- name: process
  visibility: public
  parameters:
  - name: container
  comment: null
traits:
- Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface
- Symfony\Component\DependencyInjection\Compiler\PriorityTaggedServiceTrait
- Symfony\Component\DependencyInjection\ContainerBuilder
- PriorityTaggedServiceTrait
interfaces:
- CompilerPassInterface
