name: notifications
description: Laravel-style notifications for Dart
version: 0.0.1
homepage: https://protevus.com

environment:
  sdk: ^3.4.2

dependencies:
  platform_events: ^0.0.1
  platform_queue: ^0.0.1
  platform_contracts: ^0.0.1
  platform_database: ^0.0.1
  platform_mail: ^0.0.1
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
