name: illuminate_websocket
description: Websocket library for protevus platform.
version: 1.0.0
repository: https://github.com/dartondox/dox
environment:
  sdk: ^3.1.0

dependencies:
  uuid: ^3.0.6
  illuminate_annotation: ^1.0.5
  illuminate_cache: ^0.0.1
  illuminate_contracts: ^0.0.1
  illuminate_http: ^0.0.1
  illuminate_routing: ^0.0.1
  illuminate_support: ^0.0.1
  ioredis: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  illuminate_foundation: ^2.0.0
