name: illuminate_websocket
description: Websocket library for protevus platform.
version: 0.5.1
repository: https://github.com/dartondox/dox
environment:
  sdk: ^3.1.0

dependencies:
  uuid: ^3.0.6
  illuminate_cache: ^0.5.1
  illuminate_contracts: ^0.5.1
  illuminate_http: ^0.5.1
  illuminate_routing: ^0.5.1
  illuminate_support: ^0.5.1
  ioredis: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  illuminate_foundation: ^0.5.1
