name: ErrorHandlerConfigurator
class_comment: '# * Configures the error handler.

  # *

  # * @final

  # *

  # * @internal'
dependencies:
- name: LoggerInterface
  type: class
  source: Psr\Log\LoggerInterface
- name: ErrorHandler
  type: class
  source: Symfony\Component\ErrorHandler\ErrorHandler
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: logger
    default: 'null'
  - name: levels
    default: \E_ALL
  - name: throwAt
    default: \E_ALL
  - name: scream
    default: 'true'
  - name: scope
    default: 'true'
  - name: deprecationLogger
    default: 'null'
  comment: "# * Configures the error handler.\n# *\n# * @final\n# *\n# * @internal\n\
    # */\n# class ErrorHandlerConfigurator\n# {\n# private array|int|null $levels;\n\
    # private ?int $throwAt;\n# \n# /**\n# * @param array|int|null $levels  An array\
    \ map of E_* to LogLevel::* or an integer bit field of E_* constants\n# * @param\
    \ int|null       $throwAt Thrown errors in a bit field of E_* constants, or null\
    \ to keep the current value\n# * @param bool           $scream  Enables/disables\
    \ screaming mode, where even silenced errors are logged\n# * @param bool     \
    \      $scope   Enables/disables scoping mode"
- name: configure
  visibility: public
  parameters:
  - name: handler
  comment: '# * Configures the error handler.'
- name: setDefaultLoggers
  visibility: private
  parameters:
  - name: handler
  comment: null
traits:
- Psr\Log\LoggerInterface
- Symfony\Component\ErrorHandler\ErrorHandler
interfaces: []
