name: asset_mapper
class_comment: null
dependencies:
- name: AssetMapper
  type: class
  source: Symfony\Component\AssetMapper\AssetMapper
- name: AssetMapperCompiler
  type: class
  source: Symfony\Component\AssetMapper\AssetMapperCompiler
- name: AssetMapperDevServerSubscriber
  type: class
  source: Symfony\Component\AssetMapper\AssetMapperDevServerSubscriber
- name: AssetMapperInterface
  type: class
  source: Symfony\Component\AssetMapper\AssetMapperInterface
- name: AssetMapperRepository
  type: class
  source: Symfony\Component\AssetMapper\AssetMapperRepository
- name: AssetMapperCompileCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\AssetMapperCompileCommand
- name: DebugAssetMapperCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\DebugAssetMapperCommand
- name: ImportMapAuditCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\ImportMapAuditCommand
- name: ImportMapInstallCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\ImportMapInstallCommand
- name: ImportMapOutdatedCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\ImportMapOutdatedCommand
- name: ImportMapRemoveCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\ImportMapRemoveCommand
- name: ImportMapRequireCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\ImportMapRequireCommand
- name: ImportMapUpdateCommand
  type: class
  source: Symfony\Component\AssetMapper\Command\ImportMapUpdateCommand
- name: CompiledAssetMapperConfigReader
  type: class
  source: Symfony\Component\AssetMapper\CompiledAssetMapperConfigReader
- name: CssAssetUrlCompiler
  type: class
  source: Symfony\Component\AssetMapper\Compiler\CssAssetUrlCompiler
- name: JavaScriptImportPathCompiler
  type: class
  source: Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler
- name: SourceMappingUrlsCompiler
  type: class
  source: Symfony\Component\AssetMapper\Compiler\SourceMappingUrlsCompiler
- name: CachedMappedAssetFactory
  type: class
  source: Symfony\Component\AssetMapper\Factory\CachedMappedAssetFactory
- name: MappedAssetFactory
  type: class
  source: Symfony\Component\AssetMapper\Factory\MappedAssetFactory
- name: ImportMapAuditor
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\ImportMapAuditor
- name: ImportMapConfigReader
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\ImportMapConfigReader
- name: ImportMapGenerator
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\ImportMapGenerator
- name: ImportMapManager
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\ImportMapManager
- name: ImportMapRenderer
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\ImportMapRenderer
- name: ImportMapUpdateChecker
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\ImportMapUpdateChecker
- name: ImportMapVersionChecker
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\ImportMapVersionChecker
- name: RemotePackageDownloader
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\RemotePackageDownloader
- name: RemotePackageStorage
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\RemotePackageStorage
- name: JsDelivrEsmResolver
  type: class
  source: Symfony\Component\AssetMapper\ImportMap\Resolver\JsDelivrEsmResolver
- name: MapperAwareAssetPackage
  type: class
  source: Symfony\Component\AssetMapper\MapperAwareAssetPackage
- name: LocalPublicAssetsFilesystem
  type: class
  source: Symfony\Component\AssetMapper\Path\LocalPublicAssetsFilesystem
- name: PublicAssetsPathResolver
  type: class
  source: Symfony\Component\AssetMapper\Path\PublicAssetsPathResolver
properties: []
methods: []
traits:
- Symfony\Component\AssetMapper\AssetMapper
- Symfony\Component\AssetMapper\AssetMapperCompiler
- Symfony\Component\AssetMapper\AssetMapperDevServerSubscriber
- Symfony\Component\AssetMapper\AssetMapperInterface
- Symfony\Component\AssetMapper\AssetMapperRepository
- Symfony\Component\AssetMapper\Command\AssetMapperCompileCommand
- Symfony\Component\AssetMapper\Command\DebugAssetMapperCommand
- Symfony\Component\AssetMapper\Command\ImportMapAuditCommand
- Symfony\Component\AssetMapper\Command\ImportMapInstallCommand
- Symfony\Component\AssetMapper\Command\ImportMapOutdatedCommand
- Symfony\Component\AssetMapper\Command\ImportMapRemoveCommand
- Symfony\Component\AssetMapper\Command\ImportMapRequireCommand
- Symfony\Component\AssetMapper\Command\ImportMapUpdateCommand
- Symfony\Component\AssetMapper\CompiledAssetMapperConfigReader
- Symfony\Component\AssetMapper\Compiler\CssAssetUrlCompiler
- Symfony\Component\AssetMapper\Compiler\JavaScriptImportPathCompiler
- Symfony\Component\AssetMapper\Compiler\SourceMappingUrlsCompiler
- Symfony\Component\AssetMapper\Factory\CachedMappedAssetFactory
- Symfony\Component\AssetMapper\Factory\MappedAssetFactory
- Symfony\Component\AssetMapper\ImportMap\ImportMapAuditor
- Symfony\Component\AssetMapper\ImportMap\ImportMapConfigReader
- Symfony\Component\AssetMapper\ImportMap\ImportMapGenerator
- Symfony\Component\AssetMapper\ImportMap\ImportMapManager
- Symfony\Component\AssetMapper\ImportMap\ImportMapRenderer
- Symfony\Component\AssetMapper\ImportMap\ImportMapUpdateChecker
- Symfony\Component\AssetMapper\ImportMap\ImportMapVersionChecker
- Symfony\Component\AssetMapper\ImportMap\RemotePackageDownloader
- Symfony\Component\AssetMapper\ImportMap\RemotePackageStorage
- Symfony\Component\AssetMapper\ImportMap\Resolver\JsDelivrEsmResolver
- Symfony\Component\AssetMapper\MapperAwareAssetPackage
- Symfony\Component\AssetMapper\Path\LocalPublicAssetsFilesystem
- Symfony\Component\AssetMapper\Path\PublicAssetsPathResolver
interfaces: []
