name: cache_debug
class_comment: null
dependencies:
- name: CachePoolClearerCacheWarmer
  type: class
  source: Symfony\Bundle\FrameworkBundle\CacheWarmer\CachePoolClearerCacheWarmer
- name: CacheDataCollector
  type: class
  source: Symfony\Component\Cache\DataCollector\CacheDataCollector
properties: []
methods: []
traits:
- Symfony\Bundle\FrameworkBundle\CacheWarmer\CachePoolClearerCacheWarmer
- Symfony\Component\Cache\DataCollector\CacheDataCollector
interfaces: []
