name: cache
class_comment: null
dependencies:
- name: CacheItemPoolInterface
  type: class
  source: Psr\Cache\CacheItemPoolInterface
- name: AbstractAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\AbstractAdapter
- name: AdapterInterface
  type: class
  source: Symfony\Component\Cache\Adapter\AdapterInterface
- name: ApcuAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\ApcuAdapter
- name: ArrayAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\ArrayAdapter
- name: DoctrineDbalAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\DoctrineDbalAdapter
- name: FilesystemAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\FilesystemAdapter
- name: MemcachedAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\MemcachedAdapter
- name: PdoAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\PdoAdapter
- name: ProxyAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\ProxyAdapter
- name: RedisAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\RedisAdapter
- name: RedisTagAwareAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\RedisTagAwareAdapter
- name: TagAwareAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\TagAwareAdapter
- name: DefaultMarshaller
  type: class
  source: Symfony\Component\Cache\Marshaller\DefaultMarshaller
- name: EarlyExpirationHandler
  type: class
  source: Symfony\Component\Cache\Messenger\EarlyExpirationHandler
- name: Psr6CacheClearer
  type: class
  source: Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer
- name: CacheInterface
  type: class
  source: Symfony\Contracts\Cache\CacheInterface
- name: TagAwareCacheInterface
  type: class
  source: Symfony\Contracts\Cache\TagAwareCacheInterface
properties: []
methods: []
traits:
- Psr\Cache\CacheItemPoolInterface
- Symfony\Component\Cache\Adapter\AbstractAdapter
- Symfony\Component\Cache\Adapter\AdapterInterface
- Symfony\Component\Cache\Adapter\ApcuAdapter
- Symfony\Component\Cache\Adapter\ArrayAdapter
- Symfony\Component\Cache\Adapter\DoctrineDbalAdapter
- Symfony\Component\Cache\Adapter\FilesystemAdapter
- Symfony\Component\Cache\Adapter\MemcachedAdapter
- Symfony\Component\Cache\Adapter\PdoAdapter
- Symfony\Component\Cache\Adapter\ProxyAdapter
- Symfony\Component\Cache\Adapter\RedisAdapter
- Symfony\Component\Cache\Adapter\RedisTagAwareAdapter
- Symfony\Component\Cache\Adapter\TagAwareAdapter
- Symfony\Component\Cache\Marshaller\DefaultMarshaller
- Symfony\Component\Cache\Messenger\EarlyExpirationHandler
- Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer
- Symfony\Contracts\Cache\CacheInterface
- Symfony\Contracts\Cache\TagAwareCacheInterface
interfaces: []
