name: html_sanitizer
class_comment: null
dependencies:
- name: HtmlSanitizer
  type: class
  source: Symfony\Component\HtmlSanitizer\HtmlSanitizer
- name: HtmlSanitizerConfig
  type: class
  source: Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig
- name: HtmlSanitizerInterface
  type: class
  source: Symfony\Component\HtmlSanitizer\HtmlSanitizerInterface
properties: []
methods: []
traits:
- Symfony\Component\HtmlSanitizer\HtmlSanitizer
- Symfony\Component\HtmlSanitizer\HtmlSanitizerConfig
- Symfony\Component\HtmlSanitizer\HtmlSanitizerInterface
interfaces: []
