name: http_client
class_comment: null
dependencies:
- name: HttpAsyncClient
  type: class
  source: Http\Client\HttpAsyncClient
- name: ClientInterface
  type: class
  source: Psr\Http\Client\ClientInterface
- name: ResponseFactoryInterface
  type: class
  source: Psr\Http\Message\ResponseFactoryInterface
- name: StreamFactoryInterface
  type: class
  source: Psr\Http\Message\StreamFactoryInterface
- name: HttpClient
  type: class
  source: Symfony\Component\HttpClient\HttpClient
- name: HttplugClient
  type: class
  source: Symfony\Component\HttpClient\HttplugClient
- name: PingWebhookMessageHandler
  type: class
  source: Symfony\Component\HttpClient\Messenger\PingWebhookMessageHandler
- name: Psr18Client
  type: class
  source: Symfony\Component\HttpClient\Psr18Client
- name: GenericRetryStrategy
  type: class
  source: Symfony\Component\HttpClient\Retry\GenericRetryStrategy
- name: UriTemplateHttpClient
  type: class
  source: Symfony\Component\HttpClient\UriTemplateHttpClient
- name: HttpClientInterface
  type: class
  source: Symfony\Contracts\HttpClient\HttpClientInterface
properties: []
methods: []
traits:
- Http\Client\HttpAsyncClient
- Psr\Http\Client\ClientInterface
- Psr\Http\Message\ResponseFactoryInterface
- Psr\Http\Message\StreamFactoryInterface
- Symfony\Component\HttpClient\HttpClient
- Symfony\Component\HttpClient\HttplugClient
- Symfony\Component\HttpClient\Messenger\PingWebhookMessageHandler
- Symfony\Component\HttpClient\Psr18Client
- Symfony\Component\HttpClient\Retry\GenericRetryStrategy
- Symfony\Component\HttpClient\UriTemplateHttpClient
- Symfony\Contracts\HttpClient\HttpClientInterface
interfaces: []
