name: http_client_debug
class_comment: null
dependencies:
- name: HttpClientDataCollector
  type: class
  source: Symfony\Component\HttpClient\DataCollector\HttpClientDataCollector
properties: []
methods: []
traits:
- Symfony\Component\HttpClient\DataCollector\HttpClientDataCollector
interfaces: []
