name: mailer
class_comment: null
dependencies:
- name: MailerTestCommand
  type: class
  source: Symfony\Component\Mailer\Command\MailerTestCommand
- name: EnvelopeListener
  type: class
  source: Symfony\Component\Mailer\EventListener\EnvelopeListener
- name: MessageListener
  type: class
  source: Symfony\Component\Mailer\EventListener\MessageListener
- name: MessageLoggerListener
  type: class
  source: Symfony\Component\Mailer\EventListener\MessageLoggerListener
- name: MessengerTransportListener
  type: class
  source: Symfony\Component\Mailer\EventListener\MessengerTransportListener
- name: Mailer
  type: class
  source: Symfony\Component\Mailer\Mailer
- name: MailerInterface
  type: class
  source: Symfony\Component\Mailer\MailerInterface
- name: MessageHandler
  type: class
  source: Symfony\Component\Mailer\Messenger\MessageHandler
- name: Transport
  type: class
  source: Symfony\Component\Mailer\Transport
- name: TransportInterface
  type: class
  source: Symfony\Component\Mailer\Transport\TransportInterface
- name: Transports
  type: class
  source: Symfony\Component\Mailer\Transport\Transports
properties: []
methods: []
traits:
- Symfony\Component\Mailer\Command\MailerTestCommand
- Symfony\Component\Mailer\EventListener\EnvelopeListener
- Symfony\Component\Mailer\EventListener\MessageListener
- Symfony\Component\Mailer\EventListener\MessageLoggerListener
- Symfony\Component\Mailer\EventListener\MessengerTransportListener
- Symfony\Component\Mailer\Mailer
- Symfony\Component\Mailer\MailerInterface
- Symfony\Component\Mailer\Messenger\MessageHandler
- Symfony\Component\Mailer\Transport
- Symfony\Component\Mailer\Transport\TransportInterface
- Symfony\Component\Mailer\Transport\Transports
interfaces: []
