name: mailer_transports
class_comment: null
dependencies:
- name: SesTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Amazon\Transport\SesTransportFactory
- name: AzureTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Azure\Transport\AzureTransportFactory
- name: BrevoTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Brevo\Transport\BrevoTransportFactory
- name: GmailTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Google\Transport\GmailTransportFactory
- name: InfobipTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Infobip\Transport\InfobipTransportFactory
- name: MandrillTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillTransportFactory
- name: MailerSendTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\MailerSend\Transport\MailerSendTransportFactory
- name: MailgunTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory
- name: MailjetTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetTransportFactory
- name: MailomatTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Mailomat\Transport\MailomatTransportFactory
- name: MailPaceTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\MailPace\Transport\MailPaceTransportFactory
- name: PostmarkTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkTransportFactory
- name: ResendTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Resend\Transport\ResendTransportFactory
- name: ScalewayTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Scaleway\Transport\ScalewayTransportFactory
- name: SendgridTransportFactory
  type: class
  source: Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridTransportFactory
- name: AbstractTransportFactory
  type: class
  source: Symfony\Component\Mailer\Transport\AbstractTransportFactory
- name: NativeTransportFactory
  type: class
  source: Symfony\Component\Mailer\Transport\NativeTransportFactory
- name: NullTransportFactory
  type: class
  source: Symfony\Component\Mailer\Transport\NullTransportFactory
- name: SendmailTransportFactory
  type: class
  source: Symfony\Component\Mailer\Transport\SendmailTransportFactory
- name: EsmtpTransportFactory
  type: class
  source: Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory
properties: []
methods: []
traits:
- Symfony\Component\Mailer\Bridge\Amazon\Transport\SesTransportFactory
- Symfony\Component\Mailer\Bridge\Azure\Transport\AzureTransportFactory
- Symfony\Component\Mailer\Bridge\Brevo\Transport\BrevoTransportFactory
- Symfony\Component\Mailer\Bridge\Google\Transport\GmailTransportFactory
- Symfony\Component\Mailer\Bridge\Infobip\Transport\InfobipTransportFactory
- Symfony\Component\Mailer\Bridge\Mailchimp\Transport\MandrillTransportFactory
- Symfony\Component\Mailer\Bridge\MailerSend\Transport\MailerSendTransportFactory
- Symfony\Component\Mailer\Bridge\Mailgun\Transport\MailgunTransportFactory
- Symfony\Component\Mailer\Bridge\Mailjet\Transport\MailjetTransportFactory
- Symfony\Component\Mailer\Bridge\Mailomat\Transport\MailomatTransportFactory
- Symfony\Component\Mailer\Bridge\MailPace\Transport\MailPaceTransportFactory
- Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkTransportFactory
- Symfony\Component\Mailer\Bridge\Resend\Transport\ResendTransportFactory
- Symfony\Component\Mailer\Bridge\Scaleway\Transport\ScalewayTransportFactory
- Symfony\Component\Mailer\Bridge\Sendgrid\Transport\SendgridTransportFactory
- Symfony\Component\Mailer\Transport\AbstractTransportFactory
- Symfony\Component\Mailer\Transport\NativeTransportFactory
- Symfony\Component\Mailer\Transport\NullTransportFactory
- Symfony\Component\Mailer\Transport\SendmailTransportFactory
- Symfony\Component\Mailer\Transport\Smtp\EsmtpTransportFactory
interfaces: []
