name: mailer_debug
class_comment: null
dependencies:
- name: MessageDataCollector
  type: class
  source: Symfony\Component\Mailer\DataCollector\MessageDataCollector
properties: []
methods: []
traits:
- Symfony\Component\Mailer\DataCollector\MessageDataCollector
interfaces: []
