name: messenger
class_comment: null
dependencies:
- name: ServiceLocator
  type: class
  source: Symfony\Component\DependencyInjection\ServiceLocator
- name: AmazonSqsTransportFactory
  type: class
  source: Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\AmazonSqsTransportFactory
- name: AmqpTransportFactory
  type: class
  source: Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransportFactory
- name: BeanstalkdTransportFactory
  type: class
  source: Symfony\Component\Messenger\Bridge\Beanstalkd\Transport\BeanstalkdTransportFactory
- name: RedisTransportFactory
  type: class
  source: Symfony\Component\Messenger\Bridge\Redis\Transport\RedisTransportFactory
- name: AddErrorDetailsStampListener
  type: class
  source: Symfony\Component\Messenger\EventListener\AddErrorDetailsStampListener
- name: DispatchPcntlSignalListener
  type: class
  source: Symfony\Component\Messenger\EventListener\DispatchPcntlSignalListener
- name: ResetServicesListener
  type: class
  source: Symfony\Component\Messenger\EventListener\ResetServicesListener
- name: SendFailedMessageForRetryListener
  type: class
  source: Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener
- name: SendFailedMessageToFailureTransportListener
  type: class
  source: Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener
- name: StopWorkerOnCustomStopExceptionListener
  type: class
  source: Symfony\Component\Messenger\EventListener\StopWorkerOnCustomStopExceptionListener
- name: StopWorkerOnRestartSignalListener
  type: class
  source: Symfony\Component\Messenger\EventListener\StopWorkerOnRestartSignalListener
- name: RedispatchMessageHandler
  type: class
  source: Symfony\Component\Messenger\Handler\RedispatchMessageHandler
- name: AddBusNameStampMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware
- name: DispatchAfterCurrentBusMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware
- name: FailedMessageProcessingMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware
- name: HandleMessageMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
- name: RejectRedeliveredMessageMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware
- name: RouterContextMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\RouterContextMiddleware
- name: SendMessageMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\SendMessageMiddleware
- name: TraceableMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\TraceableMiddleware
- name: ValidationMiddleware
  type: class
  source: Symfony\Component\Messenger\Middleware\ValidationMiddleware
- name: MultiplierRetryStrategy
  type: class
  source: Symfony\Component\Messenger\Retry\MultiplierRetryStrategy
- name: RoutableMessageBus
  type: class
  source: Symfony\Component\Messenger\RoutableMessageBus
- name: InMemoryTransportFactory
  type: class
  source: Symfony\Component\Messenger\Transport\InMemory\InMemoryTransportFactory
- name: SendersLocator
  type: class
  source: Symfony\Component\Messenger\Transport\Sender\SendersLocator
- name: FlattenExceptionNormalizer
  type: class
  source: Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer
- name: PhpSerializer
  type: class
  source: Symfony\Component\Messenger\Transport\Serialization\PhpSerializer
- name: Serializer
  type: class
  source: Symfony\Component\Messenger\Transport\Serialization\Serializer
- name: SerializerInterface
  type: class
  source: Symfony\Component\Messenger\Transport\Serialization\SerializerInterface
- name: SyncTransportFactory
  type: class
  source: Symfony\Component\Messenger\Transport\Sync\SyncTransportFactory
- name: TransportFactory
  type: class
  source: Symfony\Component\Messenger\Transport\TransportFactory
properties: []
methods: []
traits:
- Symfony\Component\DependencyInjection\ServiceLocator
- Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\AmazonSqsTransportFactory
- Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransportFactory
- Symfony\Component\Messenger\Bridge\Beanstalkd\Transport\BeanstalkdTransportFactory
- Symfony\Component\Messenger\Bridge\Redis\Transport\RedisTransportFactory
- Symfony\Component\Messenger\EventListener\AddErrorDetailsStampListener
- Symfony\Component\Messenger\EventListener\DispatchPcntlSignalListener
- Symfony\Component\Messenger\EventListener\ResetServicesListener
- Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener
- Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener
- Symfony\Component\Messenger\EventListener\StopWorkerOnCustomStopExceptionListener
- Symfony\Component\Messenger\EventListener\StopWorkerOnRestartSignalListener
- Symfony\Component\Messenger\Handler\RedispatchMessageHandler
- Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware
- Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware
- Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware
- Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
- Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware
- Symfony\Component\Messenger\Middleware\RouterContextMiddleware
- Symfony\Component\Messenger\Middleware\SendMessageMiddleware
- Symfony\Component\Messenger\Middleware\TraceableMiddleware
- Symfony\Component\Messenger\Middleware\ValidationMiddleware
- Symfony\Component\Messenger\Retry\MultiplierRetryStrategy
- Symfony\Component\Messenger\RoutableMessageBus
- Symfony\Component\Messenger\Transport\InMemory\InMemoryTransportFactory
- Symfony\Component\Messenger\Transport\Sender\SendersLocator
- Symfony\Component\Messenger\Transport\Serialization\Normalizer\FlattenExceptionNormalizer
- Symfony\Component\Messenger\Transport\Serialization\PhpSerializer
- Symfony\Component\Messenger\Transport\Serialization\Serializer
- Symfony\Component\Messenger\Transport\Serialization\SerializerInterface
- Symfony\Component\Messenger\Transport\Sync\SyncTransportFactory
- Symfony\Component\Messenger\Transport\TransportFactory
interfaces: []
