name: notifier_transports
class_comment: null
dependencies:
- name: Bridge
  type: class
  source: Symfony\Component\Notifier\Bridge
- name: AbstractTransportFactory
  type: class
  source: Symfony\Component\Notifier\Transport\AbstractTransportFactory
- name: NullTransportFactory
  type: class
  source: Symfony\Component\Notifier\Transport\NullTransportFactory
properties: []
methods: []
traits:
- Symfony\Component\Notifier\Bridge
- Symfony\Component\Notifier\Transport\AbstractTransportFactory
- Symfony\Component\Notifier\Transport\NullTransportFactory
interfaces: []
