name: notifier_webhook
class_comment: null
dependencies:
- name: TwilioRequestParser
  type: class
  source: Symfony\Component\Notifier\Bridge\Twilio\Webhook\TwilioRequestParser
- name: VonageRequestParser
  type: class
  source: Symfony\Component\Notifier\Bridge\Vonage\Webhook\VonageRequestParser
properties: []
methods: []
traits:
- Symfony\Component\Notifier\Bridge\Twilio\Webhook\TwilioRequestParser
- Symfony\Component\Notifier\Bridge\Vonage\Webhook\VonageRequestParser
interfaces: []
