name: secrets
class_comment: null
dependencies:
- name: DotenvVault
  type: class
  source: Symfony\Bundle\FrameworkBundle\Secrets\DotenvVault
- name: SodiumVault
  type: class
  source: Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault
- name: StaticEnvVarLoader
  type: class
  source: Symfony\Component\DependencyInjection\StaticEnvVarLoader
properties: []
methods: []
traits:
- Symfony\Bundle\FrameworkBundle\Secrets\DotenvVault
- Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault
- Symfony\Component\DependencyInjection\StaticEnvVarLoader
interfaces: []
