name: security_csrf
class_comment: null
dependencies:
- name: CsrfExtension
  type: class
  source: Symfony\Bridge\Twig\Extension\CsrfExtension
- name: CsrfRuntime
  type: class
  source: Symfony\Bridge\Twig\Extension\CsrfRuntime
- name: CsrfTokenManager
  type: class
  source: Symfony\Component\Security\Csrf\CsrfTokenManager
- name: CsrfTokenManagerInterface
  type: class
  source: Symfony\Component\Security\Csrf\CsrfTokenManagerInterface
- name: TokenGeneratorInterface
  type: class
  source: Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface
- name: UriSafeTokenGenerator
  type: class
  source: Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator
- name: SessionTokenStorage
  type: class
  source: Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage
- name: TokenStorageInterface
  type: class
  source: Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface
properties: []
methods: []
traits:
- Symfony\Bridge\Twig\Extension\CsrfExtension
- Symfony\Bridge\Twig\Extension\CsrfRuntime
- Symfony\Component\Security\Csrf\CsrfTokenManager
- Symfony\Component\Security\Csrf\CsrfTokenManagerInterface
- Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface
- Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator
- Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage
- Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface
interfaces: []
