name: serializer_debug
class_comment: null
dependencies:
- name: SerializerDataCollector
  type: class
  source: Symfony\Component\Serializer\DataCollector\SerializerDataCollector
- name: TraceableSerializer
  type: class
  source: Symfony\Component\Serializer\Debug\TraceableSerializer
properties: []
methods: []
traits:
- Symfony\Component\Serializer\DataCollector\SerializerDataCollector
- Symfony\Component\Serializer\Debug\TraceableSerializer
interfaces: []
