name: session
class_comment: null
dependencies:
- name: SessionFactory
  type: class
  source: Symfony\Component\HttpFoundation\Session\SessionFactory
- name: AbstractSessionHandler
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler
- name: IdentityMarshaller
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\Handler\IdentityMarshaller
- name: MarshallingSessionHandler
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\Handler\MarshallingSessionHandler
- name: NativeFileSessionHandler
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler
- name: SessionHandlerFactory
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\Handler\SessionHandlerFactory
- name: StrictSessionHandler
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler
- name: MetadataBag
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\MetadataBag
- name: MockFileSessionStorageFactory
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorageFactory
- name: NativeSessionStorageFactory
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorageFactory
- name: PhpBridgeSessionStorageFactory
  type: class
  source: Symfony\Component\HttpFoundation\Session\Storage\PhpBridgeSessionStorageFactory
- name: SessionListener
  type: class
  source: Symfony\Component\HttpKernel\EventListener\SessionListener
properties: []
methods: []
traits:
- Symfony\Component\HttpFoundation\Session\SessionFactory
- Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler
- Symfony\Component\HttpFoundation\Session\Storage\Handler\IdentityMarshaller
- Symfony\Component\HttpFoundation\Session\Storage\Handler\MarshallingSessionHandler
- Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler
- Symfony\Component\HttpFoundation\Session\Storage\Handler\SessionHandlerFactory
- Symfony\Component\HttpFoundation\Session\Storage\Handler\StrictSessionHandler
- Symfony\Component\HttpFoundation\Session\Storage\MetadataBag
- Symfony\Component\HttpFoundation\Session\Storage\MockFileSessionStorageFactory
- Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorageFactory
- Symfony\Component\HttpFoundation\Session\Storage\PhpBridgeSessionStorageFactory
- Symfony\Component\HttpKernel\EventListener\SessionListener
interfaces: []
