name: ssi
class_comment: null
dependencies:
- name: SurrogateListener
  type: class
  source: Symfony\Component\HttpKernel\EventListener\SurrogateListener
- name: Ssi
  type: class
  source: Symfony\Component\HttpKernel\HttpCache\Ssi
properties: []
methods: []
traits:
- Symfony\Component\HttpKernel\EventListener\SurrogateListener
- Symfony\Component\HttpKernel\HttpCache\Ssi
interfaces: []
