name: test
class_comment: null
dependencies:
- name: KernelBrowser
  type: class
  source: Symfony\Bundle\FrameworkBundle\KernelBrowser
- name: TestContainer
  type: class
  source: Symfony\Bundle\FrameworkBundle\Test\TestContainer
- name: CookieJar
  type: class
  source: Symfony\Component\BrowserKit\CookieJar
- name: History
  type: class
  source: Symfony\Component\BrowserKit\History
- name: ServiceLocator
  type: class
  source: Symfony\Component\DependencyInjection\ServiceLocator
- name: SessionListener
  type: class
  source: Symfony\Component\HttpKernel\EventListener\SessionListener
properties: []
methods: []
traits:
- Symfony\Bundle\FrameworkBundle\KernelBrowser
- Symfony\Bundle\FrameworkBundle\Test\TestContainer
- Symfony\Component\BrowserKit\CookieJar
- Symfony\Component\BrowserKit\History
- Symfony\Component\DependencyInjection\ServiceLocator
- Symfony\Component\HttpKernel\EventListener\SessionListener
interfaces: []
