name: uid
class_comment: null
dependencies:
- name: NameBasedUuidFactory
  type: class
  source: Symfony\Component\Uid\Factory\NameBasedUuidFactory
- name: RandomBasedUuidFactory
  type: class
  source: Symfony\Component\Uid\Factory\RandomBasedUuidFactory
- name: TimeBasedUuidFactory
  type: class
  source: Symfony\Component\Uid\Factory\TimeBasedUuidFactory
- name: UlidFactory
  type: class
  source: Symfony\Component\Uid\Factory\UlidFactory
- name: UuidFactory
  type: class
  source: Symfony\Component\Uid\Factory\UuidFactory
properties: []
methods: []
traits:
- Symfony\Component\Uid\Factory\NameBasedUuidFactory
- Symfony\Component\Uid\Factory\RandomBasedUuidFactory
- Symfony\Component\Uid\Factory\TimeBasedUuidFactory
- Symfony\Component\Uid\Factory\UlidFactory
- Symfony\Component\Uid\Factory\UuidFactory
interfaces: []
