name: validator
class_comment: null
dependencies:
- name: ValidatorCacheWarmer
  type: class
  source: Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer
- name: PhpArrayAdapter
  type: class
  source: Symfony\Component\Cache\Adapter\PhpArrayAdapter
- name: ExpressionLanguage
  type: class
  source: Symfony\Component\ExpressionLanguage\ExpressionLanguage
- name: EmailValidator
  type: class
  source: Symfony\Component\Validator\Constraints\EmailValidator
- name: ExpressionLanguageProvider
  type: class
  source: Symfony\Component\Validator\Constraints\ExpressionLanguageProvider
- name: ExpressionValidator
  type: class
  source: Symfony\Component\Validator\Constraints\ExpressionValidator
- name: NoSuspiciousCharactersValidator
  type: class
  source: Symfony\Component\Validator\Constraints\NoSuspiciousCharactersValidator
- name: NotCompromisedPasswordValidator
  type: class
  source: Symfony\Component\Validator\Constraints\NotCompromisedPasswordValidator
- name: WhenValidator
  type: class
  source: Symfony\Component\Validator\Constraints\WhenValidator
- name: ContainerConstraintValidatorFactory
  type: class
  source: Symfony\Component\Validator\ContainerConstraintValidatorFactory
- name: PropertyInfoLoader
  type: class
  source: Symfony\Component\Validator\Mapping\Loader\PropertyInfoLoader
- name: Validation
  type: class
  source: Symfony\Component\Validator\Validation
- name: ValidatorInterface
  type: class
  source: Symfony\Component\Validator\Validator\ValidatorInterface
- name: ValidatorBuilder
  type: class
  source: Symfony\Component\Validator\ValidatorBuilder
properties: []
methods: []
traits:
- Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer
- Symfony\Component\Cache\Adapter\PhpArrayAdapter
- Symfony\Component\ExpressionLanguage\ExpressionLanguage
- Symfony\Component\Validator\Constraints\EmailValidator
- Symfony\Component\Validator\Constraints\ExpressionLanguageProvider
- Symfony\Component\Validator\Constraints\ExpressionValidator
- Symfony\Component\Validator\Constraints\NoSuspiciousCharactersValidator
- Symfony\Component\Validator\Constraints\NotCompromisedPasswordValidator
- Symfony\Component\Validator\Constraints\WhenValidator
- Symfony\Component\Validator\ContainerConstraintValidatorFactory
- Symfony\Component\Validator\Mapping\Loader\PropertyInfoLoader
- Symfony\Component\Validator\Validation
- Symfony\Component\Validator\Validator\ValidatorInterface
- Symfony\Component\Validator\ValidatorBuilder
interfaces: []
