name: FirewallConfig
class_comment: null
dependencies: []
properties: []
methods:
- name: getRequestMatcher
  visibility: public
  parameters: []
  comment: "# * @author Robin Chalas <robin.chalas@gmail.com>\n# */\n# final class\
    \ FirewallConfig\n# {\n# public function __construct(\n# private readonly string\
    \ $name,\n# private readonly string $userChecker,\n# private readonly ?string\
    \ $requestMatcher = null,\n# private readonly bool $securityEnabled = true,\n\
    # private readonly bool $stateless = false,\n# private readonly ?string $provider\
    \ = null,\n# private readonly ?string $context = null,\n# private readonly ?string\
    \ $entryPoint = null,\n# private readonly ?string $accessDeniedHandler = null,\n\
    # private readonly ?string $accessDeniedUrl = null,\n# private readonly array\
    \ $authenticators = [],\n# private readonly ?array $switchUser = null,\n# private\
    \ readonly ?array $logout = null,\n# ) {\n# }\n# \n# public function getName():\
    \ string\n# {\n# return $this->name;\n# }\n# \n# /**\n# * @return string|null\
    \ The request matcher service id or null if neither the request matcher, pattern\
    \ or host\n# *                     options were provided"
- name: isSecurityEnabled
  visibility: public
  parameters: []
  comment: null
- name: isStateless
  visibility: public
  parameters: []
  comment: null
- name: getProvider
  visibility: public
  parameters: []
  comment: null
- name: getContext
  visibility: public
  parameters: []
  comment: '# * @return string|null The context key (will be null if the firewall
    is stateless)'
- name: getEntryPoint
  visibility: public
  parameters: []
  comment: null
- name: getUserChecker
  visibility: public
  parameters: []
  comment: null
- name: getAccessDeniedHandler
  visibility: public
  parameters: []
  comment: null
- name: getAccessDeniedUrl
  visibility: public
  parameters: []
  comment: null
- name: getAuthenticators
  visibility: public
  parameters: []
  comment: null
- name: getSwitchUser
  visibility: public
  parameters: []
  comment: null
- name: getLogout
  visibility: public
  parameters: []
  comment: null
traits: []
interfaces: []
