name: sample_app
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  illuminate_cache: ^0.5.1-dev.0+1
  illuminate_config: ^0.5.1-dev.0+1
  illuminate_contracts: ^0.5.1-dev.0+1
  illuminate_database: ^0.5.1-dev.0+1
  illuminate_foundation: ^0.5.1-dev.0+1
  illuminate_http: ^0.5.1-dev.0+1
  illuminate_log: ^0.5.1-dev.0+1
  illuminate_migration: ^0.5.1-dev.0+1
  illuminate_routing: ^0.5.1-dev.0+1
  illuminate_storage: ^0.5.1-dev.0+1
  illuminate_support: ^0.5.1-dev.0+1
  postgres: ^3.0.5

dev_dependencies:
  illuminate_builder: ^0.5.1-dev.0+1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.1.2
