name: illuminate_concurrency
description: The Concurrency Package for the Protevus Platform
version: 0.5.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

dependencies:
  meta: ^1.9.0
  path: ^1.8.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
