name: illuminate_console
description: The Console Package for the Protevus Platform
version: 0.5.2-dev.0
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platform

environment:
  sdk: ^3.4.2

dependencies:
  args: ^2.4.2
  file: ^7.0.0
  meta: ^1.9.1
  path: ^1.8.0
  collection: ^1.18.0
  ansicolor: ^2.0.2
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
