name: HeaderSignatureConfigurator
class_comment: null
dependencies:
- name: HttpOptions
  type: class
  source: Symfony\Component\HttpClient\HttpOptions
- name: RemoteEvent
  type: class
  source: Symfony\Component\RemoteEvent\RemoteEvent
- name: InvalidArgumentException
  type: class
  source: Symfony\Component\Webhook\Exception\InvalidArgumentException
- name: LogicException
  type: class
  source: Symfony\Component\Webhook\Exception\LogicException
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: algo
    default: '''sha256'''
  - name: signatureHeaderName
    default: '''Webhook-Signature'''
  comment: null
- name: configure
  visibility: public
  parameters:
  - name: event
  - name: secret
  - name: options
  comment: null
traits:
- Symfony\Component\HttpClient\HttpOptions
- Symfony\Component\RemoteEvent\RemoteEvent
- Symfony\Component\Webhook\Exception\InvalidArgumentException
- Symfony\Component\Webhook\Exception\LogicException
interfaces:
- RequestConfiguratorInterface
