name: HeadersConfigurator
class_comment: null
dependencies:
- name: HttpOptions
  type: class
  source: Symfony\Component\HttpClient\HttpOptions
- name: RemoteEvent
  type: class
  source: Symfony\Component\RemoteEvent\RemoteEvent
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: eventHeaderName
    default: '''Webhook-Event'''
  - name: idHeaderName
    default: '''Webhook-Id'''
  comment: null
- name: configure
  visibility: public
  parameters:
  - name: event
  - name: secret
  - name: options
  comment: null
traits:
- Symfony\Component\HttpClient\HttpOptions
- Symfony\Component\RemoteEvent\RemoteEvent
interfaces:
- RequestConfiguratorInterface
