name: RequestConfiguratorInterface
class_comment: null
dependencies:
- name: HttpOptions
  type: class
  source: Symfony\Component\HttpClient\HttpOptions
- name: RemoteEvent
  type: class
  source: Symfony\Component\RemoteEvent\RemoteEvent
properties: []
methods:
- name: configure
  visibility: public
  parameters:
  - name: event
  - name: secret
  - name: options
  comment: null
traits:
- Symfony\Component\HttpClient\HttpOptions
- Symfony\Component\RemoteEvent\RemoteEvent
interfaces: []
