name: platform_redis
version: 8.2.0
description: An Platform service provider for Redis. Works well for caching volatile data.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/redis
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  platform_foundation: ^8.0.0
  platform_support: ^8.0.0
  resp_client: ^1.2.0
dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   angel3_framework:
#     path: ../framework
#   angel3_container:
#     path: ../container/angel_container
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request