name: AutoconfigureTrait
class_comment: null
dependencies:
- name: InvalidArgumentException
  type: class
  source: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
properties: []
methods:
- name: autoconfigure
  visibility: public
  parameters:
  - name: autoconfigured
    default: 'true'
  comment: null
traits:
- Symfony\Component\DependencyInjection\Exception\InvalidArgumentException
interfaces: []
