name: ConfiguratorTrait
class_comment: null
dependencies:
- name: ReferenceConfigurator
  type: class
  source: Symfony\Component\DependencyInjection\Loader\Configurator\ReferenceConfigurator
properties: []
methods:
- name: configurator
  visibility: public
  parameters:
  - name: configurator
  comment: null
traits:
- Symfony\Component\DependencyInjection\Loader\Configurator\ReferenceConfigurator
interfaces: []
