name: platform_foundation
version: 9.0.0
description: Protevus Platform high-powered HTTP server extensible framework with dependency injection, routing and much more.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/core
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  platform_container: ^9.0.0
  platform_model: ^9.0.0
  platform_routing: ^9.0.0
  platform_support: ^9.0.0
  platform_testing: ^9.0.0
  platform_merge_map: ^5.1.0
  platform_combinator: ^5.2.0
  platform_http_server: ^4.4.0
  charcode: ^1.3.1
  file: ^7.0.1
  http_parser: ^4.1.1
  http2: ^2.3.0
  logging: ^1.3.0
  matcher: ^0.12.16
  meta: ^1.16.0
  mime: ^2.0.0
  path: ^1.9.1
  quiver: ^3.2.2
  recase: ^4.1.0
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  tuple: ^2.0.2
  uuid: ^4.5.1
  collection: ^1.19.1
dev_dependencies:
  http: ^1.2.2
  io: ^1.0.4
  test: ^1.25.8
  lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
# dependency_overrides:
#   platform_container:
#     path: ../container/angel_container
#   platform_http_exception:
#     path: ../http_exception
#   platform_model:
#     path: ../model
#   platform_routing:
#     path: ../route
#   platform_mock_request:
#     path: ../mock_request

