name: ConfigurationUrlParser
class_comment: null
dependencies:
- name: BaseConfigurationUrlParser
  type: class
  source: Illuminate\Support\ConfigurationUrlParser
properties: []
methods: []
traits: []
interfaces: []
