name: platform_testing
description: Testing helper files for Protevus Platform.
version: 9.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  charcode: ^1.3.1
  platform_client: ^8.0.0
  platform_foundation: ^8.0.0
  platform_support: ^8.0.0
  platform_websocket: ^8.0.0
  platform_validation: ^8.0.0
  platform_container: ^8.0.0
  http: ^1.0.0
  matcher: ^0.12.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
