name: dsr_http_message
description: A PSR-7 compatible HTTP message interface for Dart. Provides standardized interfaces for HTTP messages including requests, responses, streams, URIs, and uploaded files.
version: 0.0.1
homepage: https://dart-fig.org

environment:
  sdk: ^3.4.2

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
