name: illuminate_contracts
description: This package defines the protevus API
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  illuminate_database: ^2.1.0
  illuminate_http: ^0.0.1
  illuminate_log: ^0.0.1
  illuminate_routing: ^0.0.1
  illuminate_support: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
