name: platform_contracts
description: Core contracts for the Platform framework
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  dsr_container: ^1.0.0
  dsr_simple_cache: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
