name: blade
description: A Dart implementation of Laravel's Blade templating engine with full feature parity and API compatibility.
version: 0.1.0
homepage: https://github.com/angeldart/blade

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  source_span: ^1.10.0
  collection: ^1.18.0
  meta: ^1.9.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  mockito: ^5.4.0

topics:
  - templates
  - blade
  - laravel
  - view
  - html

funding:
  - https://github.com/sponsors/angeldart

platforms:
  linux:
  macos:
  windows:

# Additional package metadata
repository: https://github.com/angeldart/blade
issue_tracker: https://github.com/angeldart/blade/issues
documentation: https://docs.angeldart.dev/blade

# Package features
false_secrets:
  - example/**/*.html
