name: illuminate_filesystem
description: The Filesystem Package for the Protevus Platform
version: 0.5.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

dependencies:
  path: ^1.8.0
  meta: ^1.9.0
  illuminate_collections: ^0.5.1
  illuminate_conditionable: ^0.5.1
  illuminate_contracts: ^0.5.1
  illuminate_macroable: ^0.5.1
  illuminate_support: ^0.5.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
