name: platform_hashing
description: The Hashing Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  meta: ^1.9.1
  pointycastle: ^3.9.1
  illuminate_contracts: ^0.1.0
  illuminate_support: ^0.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
