name: illuminate_mail
description: The Mail Package for the Protevus Platform
version: 0.5.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  mailer: ^6.1.0
  http: ^1.2.0
  http_parser: ^4.0.2
  mustache_template: ^2.0.0
  meta: ^1.12.0
  logging: ^1.2.0
  async: ^2.11.0
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
