name: EnvironmentDetector
class_comment: null
dependencies:
- name: Closure
  type: class
  source: Closure
properties: []
methods:
- name: detect
  visibility: public
  parameters:
  - name: callback
  - name: consoleArgs
    default: 'null'
  comment: '# * Detect the application''s current environment.

    # *

    # * @param  \Closure  $callback

    # * @param  array|null  $consoleArgs

    # * @return string'
- name: detectWebEnvironment
  visibility: protected
  parameters:
  - name: callback
  comment: '# * Set the application environment for a web request.

    # *

    # * @param  \Closure  $callback

    # * @return string'
- name: detectConsoleEnvironment
  visibility: protected
  parameters:
  - name: callback
  - name: args
  comment: '# * Set the application environment from command-line arguments.

    # *

    # * @param  \Closure  $callback

    # * @param  array  $args

    # * @return string'
- name: getEnvironmentArgument
  visibility: protected
  parameters:
  - name: args
  comment: '# * Get the environment argument from the console.

    # *

    # * @param  array  $args

    # * @return string|null'
traits:
- Closure
interfaces: []
