name: platform_macroable
description: A Dart implementation of Laravel's Macroable trait, allowing runtime method extension
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  platform_reflection: ^0.1.0
  platform_contracts: ^0.1.0
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
