name: platform_macroable
description: A Dart implementation of Laravel's Macroable trait.
version: 1.0.0
homepage: https://github.com/yourusername/macroable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Add any dependencies here

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
