name: illuminate_macroable
description: A Dart implementation of Laravel's Macroable trait, allowing runtime method extension
version: 0.5.1-dev.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  illuminate_contracts: ^0.5.1-dev.0+1
  illuminate_mirrors: ^0.5.1-dev.0+1
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
