services:
  redis:
    image: redis:latest
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "redis:/data"
    networks:
      - appnet

volumes:
  redis:
    driver: local

networks:
  appnet:
