name: dsr_http_server_handler
description: A PSR-15 compatible HTTP server handler interface for Dart. Provides a standardized interface for processing HTTP server requests and producing responses.
version: 0.0.1
homepage: https://dart-fig.org

environment:
  sdk: ^3.4.2

dependencies:
  dsr_http_message: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
