name: illuminate_events
description: The Events Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

dependencies:
  illuminate_bus: ^0.0.1
  illuminate_collections: ^0.0.1
  illuminate_container: ^0.0.1
  illuminate_contracts: ^0.0.1
  illuminate_macroable: ^0.0.1
  illuminate_support: ^0.0.1
  
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
