name: platform_events
description: The Events Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: ^3.4.2

dependencies:
  platform_container: ^0.0.1
  platform_contracts: ^0.0.1
  platform_support: ^0.0.1
  platform_macroable: ^0.0.1
  platform_collections: ^0.0.1
  platform_bus: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
