name: illuminate_pagination
description: A Dart implementation of Laravel's pagination system
version: 0.5.1-dev.0+1
homepage: https://github.com/yourusername/platform

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
