name: platform_queue
description: A Dart implementation of Laravel's queue package with full feature parity and API compatibility.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
