name: platform_config
version: 8.2.0
description: Automatic YAML application configuration loader for Platform, with .env support.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/configuration
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  platform_foundation: ^8.0.0
  platform_contracts: ^1.0.0
  platform_collections: ^1.0.0
  platform_macroable: ^1.0.0
  belatuk_merge_map: ^5.0.0
  dotenv: ^4.1.0
  file: ^7.0.0
  yaml: ^3.1.0
dev_dependencies:
  io: ^1.0.0
  logging: ^1.2.0
  lints: ^4.0.0
  belatuk_pretty_logging: ^6.0.0
  test: ^1.24.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request