name: platform_config
description: A Dart implementation of Laravel's Config package for the Protevus platform.
version: 1.0.0
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platformo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  platform_contracts: ^1.0.0
  platform_collections: ^1.0.0
  platform_macroable: ^1.0.0

dev_dependencies:
  test: ^1.16.0
  lints: ^2.0.0
