name: protevus_config
description: The Configuration Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  protevus_runtime: ^0.0.1
  meta: ^1.3.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
