name: illuminate_container
version: 0.5.1
description: Protevus Platform hierarchical DI container, and pluggable backends for reflection.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/container/container
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  collection: ^1.19.1
  quiver: ^3.2.2
dev_dependencies:
  test: ^1.25.8
  lints: ^4.0.0
