name: illuminate_pipeline
description: The Pipeline Package for the Protevus Platform
version: 0.0.1
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://github.com/protevus/platform

environment:
  sdk: ^3.4.2

# Add regular dependencies here.
dependencies:
  illuminate_conditionable: ^9.0.0
  illuminate_container: ^9.0.0
  illuminate_foundation: ^2.0.0
  logging: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
