name: Repository
class_comment: null
dependencies: []
properties: []
methods:
- name: has
  visibility: public
  parameters:
  - name: key
  comment: '# * Determine if the given configuration value exists.

    # *

    # * @param  string  $key

    # * @return bool'
- name: get
  visibility: public
  parameters:
  - name: key
  - name: default
    default: 'null'
  comment: '# * Get the specified configuration value.

    # *

    # * @param  array|string  $key

    # * @param  mixed  $default

    # * @return mixed'
- name: all
  visibility: public
  parameters: []
  comment: '# * Get all of the configuration items for the application.

    # *

    # * @return array'
- name: set
  visibility: public
  parameters:
  - name: key
  - name: value
    default: 'null'
  comment: '# * Set a given configuration value.

    # *

    # * @param  array|string  $key

    # * @param  mixed  $value

    # * @return void'
- name: prepend
  visibility: public
  parameters:
  - name: key
  - name: value
  comment: '# * Prepend a value onto an array configuration value.

    # *

    # * @param  string  $key

    # * @param  mixed  $value

    # * @return void'
- name: push
  visibility: public
  parameters:
  - name: key
  - name: value
  comment: '# * Push a value onto an array configuration value.

    # *

    # * @param  string  $key

    # * @param  mixed  $value

    # * @return void'
traits: []
interfaces: []
