services:
  rethinkdb:
    image: rethinkdb:latest
    restart: "no"
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    volumes:
      - "rethinkdb:/data"
    networks:
      - appnet

volumes:
  rethinkdb:
    driver: local

networks:
  appnet:
