name: illuminate_builder
description: Builder for protevus platform
version: 0.5.1-dev.0+1
repository: https://github.com/dartondox/dox
homepage: https://dartondox.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.0
  source_gen: ^1.3.1
  analyzer: ^5.12.0
  illuminate_database: ^0.5.1-dev.0+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
