name: MergeExtensionConfigurationPass
class_comment: '# * Ensures certain extensions are always loaded.

  # *

  # * @author Kris Wallsmith <kris@symfony.com>'
dependencies:
- name: BaseMergeExtensionConfigurationPass
  type: class
  source: Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass
- name: ContainerBuilder
  type: class
  source: Symfony\Component\DependencyInjection\ContainerBuilder
properties: []
methods:
- name: __construct
  visibility: public
  parameters:
  - name: extensions
  comment: '# * Ensures certain extensions are always loaded.

    # *

    # * @author Kris Wallsmith <kris@symfony.com>

    # */

    # class MergeExtensionConfigurationPass extends BaseMergeExtensionConfigurationPass

    # {

    # /**

    # * @param string[] $extensions'
- name: process
  visibility: public
  parameters:
  - name: container
  comment: null
traits:
- Symfony\Component\DependencyInjection\ContainerBuilder
interfaces: []
