name: dsr_clock
description: A PSR-20 compatible clock interface for Dart. Provides a minimal, standardized interface for reading the current time across different implementations.
version: 0.0.1
homepage: https://dart-fig.org

environment:
  sdk: ^3.4.2

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
