name: example_eloquent
version: 1.0.0
description: example of platform_database
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  platform_database:
    path: ../

#dev_dependencies:
 