name: illuminate_bus
description: Bus implementation for the Platform framework
version: 0.5.1-dev.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  illuminate_collections: ^0.5.1-dev.0+1
  illuminate_container: ^0.5.1-dev.0+1
  illuminate_contracts: ^0.5.1-dev.0+1
  illuminate_pipeline: ^0.5.1-dev.0+1
  illuminate_support: ^0.5.1-dev.0+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
