name: illuminate_bus
description: Bus implementation for the Platform framework
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  illuminate_collections: ^2.0.0
  illuminate_container: ^9.0.0
  illuminate_contracts: ^9.0.0
  illuminate_pipeline: ^9.0.0
  illuminate_support: ^9.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
