name: CanConfigureMigrationCommands
class_comment: null
dependencies: []
properties: []
methods:
- name: migrateFreshUsing
  visibility: protected
  parameters: []
  comment: '# * The parameters that should be used when running "migrate:fresh".

    # *

    # * @return array'
- name: shouldDropViews
  visibility: protected
  parameters: []
  comment: '# * Determine if views should be dropped when refreshing the database.

    # *

    # * @return bool'
- name: shouldDropTypes
  visibility: protected
  parameters: []
  comment: '# * Determine if types should be dropped when refreshing the database.

    # *

    # * @return bool'
- name: shouldSeed
  visibility: protected
  parameters: []
  comment: '# * Determine if the seed task should be run when refreshing the database.

    # *

    # * @return bool'
- name: seeder
  visibility: protected
  parameters: []
  comment: '# * Determine the specific seeder class that should be used when refreshing
    the database.

    # *

    # * @return mixed'
traits: []
interfaces: []
