// Mocks generated by Mockito 5.4.4 from annotations
// in platform_container/test/container_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:platform_contracts/src/reflection/base.dart' as _i2;
import 'package:platform_contracts/src/reflection/reflector_contract.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTypeMirror_0 extends _i1.SmartFake implements _i2.TypeMirror {
  _FakeTypeMirror_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInstanceMirror_1 extends _i1.SmartFake
    implements _i2.InstanceMirror {
  _FakeInstanceMirror_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLibraryMirror_2 extends _i1.SmartFake implements _i2.LibraryMirror {
  _FakeLibraryMirror_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeType_3 extends _i1.SmartFake implements Type {
  _FakeType_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSymbol_4 extends _i1.SmartFake implements Symbol {
  _FakeSymbol_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassMirror_5 extends _i1.SmartFake implements _i2.ClassMirror {
  _FakeClassMirror_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReflectorContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockReflectorContract extends _i1.Mock implements _i3.ReflectorContract {
  MockReflectorContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClassMirror? reflectClass(Type? type) =>
      (super.noSuchMethod(Invocation.method(
        #reflectClass,
        [type],
      )) as _i2.ClassMirror?);

  @override
  _i2.TypeMirror reflectType(Type? type) => (super.noSuchMethod(
        Invocation.method(
          #reflectType,
          [type],
        ),
        returnValue: _FakeTypeMirror_0(
          this,
          Invocation.method(
            #reflectType,
            [type],
          ),
        ),
      ) as _i2.TypeMirror);

  @override
  _i2.InstanceMirror reflect(Object? object) => (super.noSuchMethod(
        Invocation.method(
          #reflect,
          [object],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #reflect,
            [object],
          ),
        ),
      ) as _i2.InstanceMirror);

  @override
  _i2.LibraryMirror reflectLibrary(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #reflectLibrary,
          [uri],
        ),
        returnValue: _FakeLibraryMirror_2(
          this,
          Invocation.method(
            #reflectLibrary,
            [uri],
          ),
        ),
      ) as _i2.LibraryMirror);

  @override
  dynamic createInstance(
    Type? type, {
    List<dynamic>? positionalArgs,
    Map<String, dynamic>? namedArgs,
    String? constructorName,
  }) =>
      super.noSuchMethod(Invocation.method(
        #createInstance,
        [type],
        {
          #positionalArgs: positionalArgs,
          #namedArgs: namedArgs,
          #constructorName: constructorName,
        },
      ));
}

/// A class which mocks [ClassMirror].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassMirror extends _i1.Mock implements _i2.ClassMirror {
  MockClassMirror() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.ClassMirror> get superinterfaces => (super.noSuchMethod(
        Invocation.getter(#superinterfaces),
        returnValue: <_i2.ClassMirror>[],
      ) as List<_i2.ClassMirror>);

  @override
  bool get isAbstract => (super.noSuchMethod(
        Invocation.getter(#isAbstract),
        returnValue: false,
      ) as bool);

  @override
  bool get isEnum => (super.noSuchMethod(
        Invocation.getter(#isEnum),
        returnValue: false,
      ) as bool);

  @override
  Map<Symbol, _i2.DeclarationMirror> get declarations => (super.noSuchMethod(
        Invocation.getter(#declarations),
        returnValue: <Symbol, _i2.DeclarationMirror>{},
      ) as Map<Symbol, _i2.DeclarationMirror>);

  @override
  Map<Symbol, _i2.MethodMirror> get instanceMembers => (super.noSuchMethod(
        Invocation.getter(#instanceMembers),
        returnValue: <Symbol, _i2.MethodMirror>{},
      ) as Map<Symbol, _i2.MethodMirror>);

  @override
  Map<Symbol, _i2.MethodMirror> get staticMembers => (super.noSuchMethod(
        Invocation.getter(#staticMembers),
        returnValue: <Symbol, _i2.MethodMirror>{},
      ) as Map<Symbol, _i2.MethodMirror>);

  @override
  bool get hasReflectedType => (super.noSuchMethod(
        Invocation.getter(#hasReflectedType),
        returnValue: false,
      ) as bool);

  @override
  Type get reflectedType => (super.noSuchMethod(
        Invocation.getter(#reflectedType),
        returnValue: _FakeType_3(
          this,
          Invocation.getter(#reflectedType),
        ),
      ) as Type);

  @override
  List<_i2.TypeVariableMirror> get typeVariables => (super.noSuchMethod(
        Invocation.getter(#typeVariables),
        returnValue: <_i2.TypeVariableMirror>[],
      ) as List<_i2.TypeVariableMirror>);

  @override
  List<_i2.TypeMirror> get typeArguments => (super.noSuchMethod(
        Invocation.getter(#typeArguments),
        returnValue: <_i2.TypeMirror>[],
      ) as List<_i2.TypeMirror>);

  @override
  bool get isOriginalDeclaration => (super.noSuchMethod(
        Invocation.getter(#isOriginalDeclaration),
        returnValue: false,
      ) as bool);

  @override
  _i2.TypeMirror get originalDeclaration => (super.noSuchMethod(
        Invocation.getter(#originalDeclaration),
        returnValue: _FakeTypeMirror_0(
          this,
          Invocation.getter(#originalDeclaration),
        ),
      ) as _i2.TypeMirror);

  @override
  Symbol get simpleName => (super.noSuchMethod(
        Invocation.getter(#simpleName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#simpleName),
        ),
      ) as Symbol);

  @override
  Symbol get qualifiedName => (super.noSuchMethod(
        Invocation.getter(#qualifiedName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#qualifiedName),
        ),
      ) as Symbol);

  @override
  bool get isPrivate => (super.noSuchMethod(
        Invocation.getter(#isPrivate),
        returnValue: false,
      ) as bool);

  @override
  bool get isTopLevel => (super.noSuchMethod(
        Invocation.getter(#isTopLevel),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.InstanceMirror> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <_i2.InstanceMirror>[],
      ) as List<_i2.InstanceMirror>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i2.InstanceMirror newInstance(
    Symbol? constructorName,
    List<dynamic>? positionalArguments, [
    Map<Symbol, dynamic>? namedArguments = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #newInstance,
          [
            constructorName,
            positionalArguments,
            namedArguments,
          ],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #newInstance,
            [
              constructorName,
              positionalArguments,
              namedArguments,
            ],
          ),
        ),
      ) as _i2.InstanceMirror);

  @override
  bool isSubclassOf(_i2.ClassMirror? other) => (super.noSuchMethod(
        Invocation.method(
          #isSubclassOf,
          [other],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isSubtypeOf(_i2.TypeMirror? other) => (super.noSuchMethod(
        Invocation.method(
          #isSubtypeOf,
          [other],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isAssignableTo(_i2.TypeMirror? other) => (super.noSuchMethod(
        Invocation.method(
          #isAssignableTo,
          [other],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.InstanceMirror invoke(
    Symbol? memberName,
    List<dynamic>? positionalArguments, [
    Map<Symbol, dynamic>? namedArguments = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [
            memberName,
            positionalArguments,
            namedArguments,
          ],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #invoke,
            [
              memberName,
              positionalArguments,
              namedArguments,
            ],
          ),
        ),
      ) as _i2.InstanceMirror);

  @override
  _i2.InstanceMirror getField(Symbol? fieldName) => (super.noSuchMethod(
        Invocation.method(
          #getField,
          [fieldName],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #getField,
            [fieldName],
          ),
        ),
      ) as _i2.InstanceMirror);

  @override
  _i2.InstanceMirror setField(
    Symbol? fieldName,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setField,
          [
            fieldName,
            value,
          ],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #setField,
            [
              fieldName,
              value,
            ],
          ),
        ),
      ) as _i2.InstanceMirror);
}

/// A class which mocks [InstanceMirror].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstanceMirror extends _i1.Mock implements _i2.InstanceMirror {
  MockInstanceMirror() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClassMirror get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _FakeClassMirror_5(
          this,
          Invocation.getter(#type),
        ),
      ) as _i2.ClassMirror);

  @override
  bool get hasReflectee => (super.noSuchMethod(
        Invocation.getter(#hasReflectee),
        returnValue: false,
      ) as bool);

  @override
  _i2.InstanceMirror invoke(
    Symbol? memberName,
    List<dynamic>? positionalArguments, [
    Map<Symbol, dynamic>? namedArguments = const {},
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [
            memberName,
            positionalArguments,
            namedArguments,
          ],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #invoke,
            [
              memberName,
              positionalArguments,
              namedArguments,
            ],
          ),
        ),
      ) as _i2.InstanceMirror);

  @override
  _i2.InstanceMirror getField(Symbol? fieldName) => (super.noSuchMethod(
        Invocation.method(
          #getField,
          [fieldName],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #getField,
            [fieldName],
          ),
        ),
      ) as _i2.InstanceMirror);

  @override
  _i2.InstanceMirror setField(
    Symbol? fieldName,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setField,
          [
            fieldName,
            value,
          ],
        ),
        returnValue: _FakeInstanceMirror_1(
          this,
          Invocation.method(
            #setField,
            [
              fieldName,
              value,
            ],
          ),
        ),
      ) as _i2.InstanceMirror);
}

/// A class which mocks [MethodMirror].
///
/// See the documentation for Mockito's code generation for more information.
class MockMethodMirror extends _i1.Mock implements _i2.MethodMirror {
  MockMethodMirror() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TypeMirror get returnType => (super.noSuchMethod(
        Invocation.getter(#returnType),
        returnValue: _FakeTypeMirror_0(
          this,
          Invocation.getter(#returnType),
        ),
      ) as _i2.TypeMirror);

  @override
  List<_i2.ParameterMirror> get parameters => (super.noSuchMethod(
        Invocation.getter(#parameters),
        returnValue: <_i2.ParameterMirror>[],
      ) as List<_i2.ParameterMirror>);

  @override
  bool get isStatic => (super.noSuchMethod(
        Invocation.getter(#isStatic),
        returnValue: false,
      ) as bool);

  @override
  bool get isAbstract => (super.noSuchMethod(
        Invocation.getter(#isAbstract),
        returnValue: false,
      ) as bool);

  @override
  bool get isSynthetic => (super.noSuchMethod(
        Invocation.getter(#isSynthetic),
        returnValue: false,
      ) as bool);

  @override
  bool get isRegularMethod => (super.noSuchMethod(
        Invocation.getter(#isRegularMethod),
        returnValue: false,
      ) as bool);

  @override
  bool get isOperator => (super.noSuchMethod(
        Invocation.getter(#isOperator),
        returnValue: false,
      ) as bool);

  @override
  bool get isGetter => (super.noSuchMethod(
        Invocation.getter(#isGetter),
        returnValue: false,
      ) as bool);

  @override
  bool get isSetter => (super.noSuchMethod(
        Invocation.getter(#isSetter),
        returnValue: false,
      ) as bool);

  @override
  bool get isConstructor => (super.noSuchMethod(
        Invocation.getter(#isConstructor),
        returnValue: false,
      ) as bool);

  @override
  Symbol get constructorName => (super.noSuchMethod(
        Invocation.getter(#constructorName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#constructorName),
        ),
      ) as Symbol);

  @override
  bool get isConstConstructor => (super.noSuchMethod(
        Invocation.getter(#isConstConstructor),
        returnValue: false,
      ) as bool);

  @override
  bool get isGenerativeConstructor => (super.noSuchMethod(
        Invocation.getter(#isGenerativeConstructor),
        returnValue: false,
      ) as bool);

  @override
  bool get isRedirectingConstructor => (super.noSuchMethod(
        Invocation.getter(#isRedirectingConstructor),
        returnValue: false,
      ) as bool);

  @override
  bool get isFactoryConstructor => (super.noSuchMethod(
        Invocation.getter(#isFactoryConstructor),
        returnValue: false,
      ) as bool);

  @override
  Symbol get simpleName => (super.noSuchMethod(
        Invocation.getter(#simpleName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#simpleName),
        ),
      ) as Symbol);

  @override
  Symbol get qualifiedName => (super.noSuchMethod(
        Invocation.getter(#qualifiedName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#qualifiedName),
        ),
      ) as Symbol);

  @override
  bool get isPrivate => (super.noSuchMethod(
        Invocation.getter(#isPrivate),
        returnValue: false,
      ) as bool);

  @override
  bool get isTopLevel => (super.noSuchMethod(
        Invocation.getter(#isTopLevel),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.InstanceMirror> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <_i2.InstanceMirror>[],
      ) as List<_i2.InstanceMirror>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);
}

/// A class which mocks [TypeMirror].
///
/// See the documentation for Mockito's code generation for more information.
class MockTypeMirror extends _i1.Mock implements _i2.TypeMirror {
  MockTypeMirror() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasReflectedType => (super.noSuchMethod(
        Invocation.getter(#hasReflectedType),
        returnValue: false,
      ) as bool);

  @override
  Type get reflectedType => (super.noSuchMethod(
        Invocation.getter(#reflectedType),
        returnValue: _FakeType_3(
          this,
          Invocation.getter(#reflectedType),
        ),
      ) as Type);

  @override
  List<_i2.TypeVariableMirror> get typeVariables => (super.noSuchMethod(
        Invocation.getter(#typeVariables),
        returnValue: <_i2.TypeVariableMirror>[],
      ) as List<_i2.TypeVariableMirror>);

  @override
  List<_i2.TypeMirror> get typeArguments => (super.noSuchMethod(
        Invocation.getter(#typeArguments),
        returnValue: <_i2.TypeMirror>[],
      ) as List<_i2.TypeMirror>);

  @override
  bool get isOriginalDeclaration => (super.noSuchMethod(
        Invocation.getter(#isOriginalDeclaration),
        returnValue: false,
      ) as bool);

  @override
  _i2.TypeMirror get originalDeclaration => (super.noSuchMethod(
        Invocation.getter(#originalDeclaration),
        returnValue: _FakeTypeMirror_0(
          this,
          Invocation.getter(#originalDeclaration),
        ),
      ) as _i2.TypeMirror);

  @override
  Symbol get simpleName => (super.noSuchMethod(
        Invocation.getter(#simpleName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#simpleName),
        ),
      ) as Symbol);

  @override
  Symbol get qualifiedName => (super.noSuchMethod(
        Invocation.getter(#qualifiedName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#qualifiedName),
        ),
      ) as Symbol);

  @override
  bool get isPrivate => (super.noSuchMethod(
        Invocation.getter(#isPrivate),
        returnValue: false,
      ) as bool);

  @override
  bool get isTopLevel => (super.noSuchMethod(
        Invocation.getter(#isTopLevel),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.InstanceMirror> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <_i2.InstanceMirror>[],
      ) as List<_i2.InstanceMirror>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool isSubtypeOf(_i2.TypeMirror? other) => (super.noSuchMethod(
        Invocation.method(
          #isSubtypeOf,
          [other],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isAssignableTo(_i2.TypeMirror? other) => (super.noSuchMethod(
        Invocation.method(
          #isAssignableTo,
          [other],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [ParameterMirror].
///
/// See the documentation for Mockito's code generation for more information.
class MockParameterMirror extends _i1.Mock implements _i2.ParameterMirror {
  MockParameterMirror() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOptional => (super.noSuchMethod(
        Invocation.getter(#isOptional),
        returnValue: false,
      ) as bool);

  @override
  bool get isNamed => (super.noSuchMethod(
        Invocation.getter(#isNamed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasDefaultValue => (super.noSuchMethod(
        Invocation.getter(#hasDefaultValue),
        returnValue: false,
      ) as bool);

  @override
  _i2.TypeMirror get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _FakeTypeMirror_0(
          this,
          Invocation.getter(#type),
        ),
      ) as _i2.TypeMirror);

  @override
  bool get isStatic => (super.noSuchMethod(
        Invocation.getter(#isStatic),
        returnValue: false,
      ) as bool);

  @override
  bool get isFinal => (super.noSuchMethod(
        Invocation.getter(#isFinal),
        returnValue: false,
      ) as bool);

  @override
  bool get isConst => (super.noSuchMethod(
        Invocation.getter(#isConst),
        returnValue: false,
      ) as bool);

  @override
  Symbol get simpleName => (super.noSuchMethod(
        Invocation.getter(#simpleName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#simpleName),
        ),
      ) as Symbol);

  @override
  Symbol get qualifiedName => (super.noSuchMethod(
        Invocation.getter(#qualifiedName),
        returnValue: _FakeSymbol_4(
          this,
          Invocation.getter(#qualifiedName),
        ),
      ) as Symbol);

  @override
  bool get isPrivate => (super.noSuchMethod(
        Invocation.getter(#isPrivate),
        returnValue: false,
      ) as bool);

  @override
  bool get isTopLevel => (super.noSuchMethod(
        Invocation.getter(#isTopLevel),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.InstanceMirror> get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: <_i2.InstanceMirror>[],
      ) as List<_i2.InstanceMirror>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);
}
