// Mocks generated by Mockito 5.4.4 from annotations
// in platform_illuminate_container/test/laravel_container_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:platform_contracts/src/reflection/reflector_contract.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReflectedTypeContract_0 extends _i1.SmartFake
    implements _i2.ReflectedTypeContract {
  _FakeReflectedTypeContract_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeType_1 extends _i1.SmartFake implements Type {
  _FakeType_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReflectedInstanceContract_2 extends _i1.SmartFake
    implements _i2.ReflectedInstanceContract {
  _FakeReflectedInstanceContract_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReflectedClassContract_3 extends _i1.SmartFake
    implements _i2.ReflectedClassContract {
  _FakeReflectedClassContract_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReflectorContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockReflectorContract extends _i1.Mock implements _i2.ReflectorContract {
  MockReflectorContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? getName(Symbol? symbol) => (super.noSuchMethod(Invocation.method(
        #getName,
        [symbol],
      )) as String?);

  @override
  _i2.ReflectedClassContract? reflectClass(Type? clazz) =>
      (super.noSuchMethod(Invocation.method(
        #reflectClass,
        [clazz],
      )) as _i2.ReflectedClassContract?);

  @override
  _i2.ReflectedFunctionContract? reflectFunction(Function? function) =>
      (super.noSuchMethod(Invocation.method(
        #reflectFunction,
        [function],
      )) as _i2.ReflectedFunctionContract?);

  @override
  _i2.ReflectedTypeContract? reflectType(Type? type) =>
      (super.noSuchMethod(Invocation.method(
        #reflectType,
        [type],
      )) as _i2.ReflectedTypeContract?);

  @override
  _i2.ReflectedInstanceContract? reflectInstance(Object? object) =>
      (super.noSuchMethod(Invocation.method(
        #reflectInstance,
        [object],
      )) as _i2.ReflectedInstanceContract?);

  @override
  _i2.ReflectedTypeContract reflectFutureOf(Type? type) => (super.noSuchMethod(
        Invocation.method(
          #reflectFutureOf,
          [type],
        ),
        returnValue: _FakeReflectedTypeContract_0(
          this,
          Invocation.method(
            #reflectFutureOf,
            [type],
          ),
        ),
      ) as _i2.ReflectedTypeContract);
}

/// A class which mocks [ReflectedClassContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockReflectedClassContract extends _i1.Mock
    implements _i2.ReflectedClassContract {
  MockReflectedClassContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.ReflectedInstanceContract> get annotations => (super.noSuchMethod(
        Invocation.getter(#annotations),
        returnValue: <_i2.ReflectedInstanceContract>[],
      ) as List<_i2.ReflectedInstanceContract>);

  @override
  List<_i2.ReflectedFunctionContract> get constructors => (super.noSuchMethod(
        Invocation.getter(#constructors),
        returnValue: <_i2.ReflectedFunctionContract>[],
      ) as List<_i2.ReflectedFunctionContract>);

  @override
  List<_i2.ReflectedDeclarationContract> get declarations =>
      (super.noSuchMethod(
        Invocation.getter(#declarations),
        returnValue: <_i2.ReflectedDeclarationContract>[],
      ) as List<_i2.ReflectedDeclarationContract>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  List<_i2.ReflectedTypeParameterContract> get typeParameters =>
      (super.noSuchMethod(
        Invocation.getter(#typeParameters),
        returnValue: <_i2.ReflectedTypeParameterContract>[],
      ) as List<_i2.ReflectedTypeParameterContract>);

  @override
  Type get reflectedType => (super.noSuchMethod(
        Invocation.getter(#reflectedType),
        returnValue: _FakeType_1(
          this,
          Invocation.getter(#reflectedType),
        ),
      ) as Type);

  @override
  bool isAssignableTo(_i2.ReflectedTypeContract? other) => (super.noSuchMethod(
        Invocation.method(
          #isAssignableTo,
          [other],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.ReflectedInstanceContract newInstance(
    String? constructorName,
    List<dynamic>? positionalArguments, [
    Map<String, dynamic>? namedArguments = const {},
    List<Type>? typeArguments = const [],
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #newInstance,
          [
            constructorName,
            positionalArguments,
            namedArguments,
            typeArguments,
          ],
        ),
        returnValue: _FakeReflectedInstanceContract_2(
          this,
          Invocation.method(
            #newInstance,
            [
              constructorName,
              positionalArguments,
              namedArguments,
              typeArguments,
            ],
          ),
        ),
      ) as _i2.ReflectedInstanceContract);
}

/// A class which mocks [ReflectedInstanceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockReflectedInstanceContract extends _i1.Mock
    implements _i2.ReflectedInstanceContract {
  MockReflectedInstanceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ReflectedTypeContract get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _FakeReflectedTypeContract_0(
          this,
          Invocation.getter(#type),
        ),
      ) as _i2.ReflectedTypeContract);

  @override
  _i2.ReflectedClassContract get clazz => (super.noSuchMethod(
        Invocation.getter(#clazz),
        returnValue: _FakeReflectedClassContract_3(
          this,
          Invocation.getter(#clazz),
        ),
      ) as _i2.ReflectedClassContract);

  @override
  _i2.ReflectedInstanceContract getField(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getField,
          [name],
        ),
        returnValue: _FakeReflectedInstanceContract_2(
          this,
          Invocation.method(
            #getField,
            [name],
          ),
        ),
      ) as _i2.ReflectedInstanceContract);
}

/// A class which mocks [ReflectedFunctionContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockReflectedFunctionContract extends _i1.Mock
    implements _i2.ReflectedFunctionContract {
  MockReflectedFunctionContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  List<_i2.ReflectedTypeParameterContract> get typeParameters =>
      (super.noSuchMethod(
        Invocation.getter(#typeParameters),
        returnValue: <_i2.ReflectedTypeParameterContract>[],
      ) as List<_i2.ReflectedTypeParameterContract>);

  @override
  List<_i2.ReflectedInstanceContract> get annotations => (super.noSuchMethod(
        Invocation.getter(#annotations),
        returnValue: <_i2.ReflectedInstanceContract>[],
      ) as List<_i2.ReflectedInstanceContract>);

  @override
  List<_i2.ReflectedParameterContract> get parameters => (super.noSuchMethod(
        Invocation.getter(#parameters),
        returnValue: <_i2.ReflectedParameterContract>[],
      ) as List<_i2.ReflectedParameterContract>);

  @override
  bool get isGetter => (super.noSuchMethod(
        Invocation.getter(#isGetter),
        returnValue: false,
      ) as bool);

  @override
  bool get isSetter => (super.noSuchMethod(
        Invocation.getter(#isSetter),
        returnValue: false,
      ) as bool);

  @override
  _i2.ReflectedInstanceContract invoke(Invocation? invocation) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [invocation],
        ),
        returnValue: _FakeReflectedInstanceContract_2(
          this,
          Invocation.method(
            #invoke,
            [invocation],
          ),
        ),
      ) as _i2.ReflectedInstanceContract);
}

/// A class which mocks [ReflectedParameterContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockReflectedParameterContract extends _i1.Mock
    implements _i2.ReflectedParameterContract {
  MockReflectedParameterContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  List<_i2.ReflectedInstanceContract> get annotations => (super.noSuchMethod(
        Invocation.getter(#annotations),
        returnValue: <_i2.ReflectedInstanceContract>[],
      ) as List<_i2.ReflectedInstanceContract>);

  @override
  _i2.ReflectedTypeContract get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _FakeReflectedTypeContract_0(
          this,
          Invocation.getter(#type),
        ),
      ) as _i2.ReflectedTypeContract);

  @override
  bool get isRequired => (super.noSuchMethod(
        Invocation.getter(#isRequired),
        returnValue: false,
      ) as bool);

  @override
  bool get isNamed => (super.noSuchMethod(
        Invocation.getter(#isNamed),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [ReflectedTypeContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockReflectedTypeContract extends _i1.Mock
    implements _i2.ReflectedTypeContract {
  MockReflectedTypeContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  List<_i2.ReflectedTypeParameterContract> get typeParameters =>
      (super.noSuchMethod(
        Invocation.getter(#typeParameters),
        returnValue: <_i2.ReflectedTypeParameterContract>[],
      ) as List<_i2.ReflectedTypeParameterContract>);

  @override
  Type get reflectedType => (super.noSuchMethod(
        Invocation.getter(#reflectedType),
        returnValue: _FakeType_1(
          this,
          Invocation.getter(#reflectedType),
        ),
      ) as Type);

  @override
  bool isAssignableTo(_i2.ReflectedTypeContract? other) => (super.noSuchMethod(
        Invocation.method(
          #isAssignableTo,
          [other],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.ReflectedInstanceContract newInstance(
    String? constructorName,
    List<dynamic>? positionalArguments, [
    Map<String, dynamic>? namedArguments = const {},
    List<Type>? typeArguments = const [],
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #newInstance,
          [
            constructorName,
            positionalArguments,
            namedArguments,
            typeArguments,
          ],
        ),
        returnValue: _FakeReflectedInstanceContract_2(
          this,
          Invocation.method(
            #newInstance,
            [
              constructorName,
              positionalArguments,
              namedArguments,
              typeArguments,
            ],
          ),
        ),
      ) as _i2.ReflectedInstanceContract);
}
