name: ConfiguresPrompts
class_comment: null
dependencies:
- name: PromptValidationException
  type: class
  source: Illuminate\Console\PromptValidationException
- name: ConfirmPrompt
  type: class
  source: Laravel\Prompts\ConfirmPrompt
- name: MultiSearchPrompt
  type: class
  source: Laravel\Prompts\MultiSearchPrompt
- name: MultiSelectPrompt
  type: class
  source: Laravel\Prompts\MultiSelectPrompt
- name: PasswordPrompt
  type: class
  source: Laravel\Prompts\PasswordPrompt
- name: Prompt
  type: class
  source: Laravel\Prompts\Prompt
- name: SearchPrompt
  type: class
  source: Laravel\Prompts\SearchPrompt
- name: SelectPrompt
  type: class
  source: Laravel\Prompts\SelectPrompt
- name: SuggestPrompt
  type: class
  source: Laravel\Prompts\SuggestPrompt
- name: TextareaPrompt
  type: class
  source: Laravel\Prompts\TextareaPrompt
- name: TextPrompt
  type: class
  source: Laravel\Prompts\TextPrompt
- name: stdClass
  type: class
  source: stdClass
- name: InputInterface
  type: class
  source: Symfony\Component\Console\Input\InputInterface
properties: []
methods:
- name: configurePrompts
  visibility: protected
  parameters:
  - name: input
  comment: '# * Configure the prompt fallbacks.

    # *

    # * @param  \Symfony\Component\Console\Input\InputInterface  $input

    # * @return void'
- name: promptUntilValid
  visibility: protected
  parameters:
  - name: prompt
  - name: required
  - name: validate
  comment: '# * Prompt the user until the given validation callback passes.

    # *

    # * @param  \Closure  $prompt

    # * @param  bool|string  $required

    # * @param  \Closure|null  $validate

    # * @return mixed'
- name: validatePrompt
  visibility: protected
  parameters:
  - name: value
  - name: rules
  comment: '# * Validate the given prompt value using the validator.

    # *

    # * @param  mixed  $value

    # * @param  mixed  $rules

    # * @return ?string'
- name: getPromptValidatorInstance
  visibility: protected
  parameters:
  - name: field
  - name: value
  - name: rules
  - name: messages
    default: '[]'
  - name: attributes
    default: '[]'
  comment: '# * Get the validator instance that should be used to validate prompts.

    # *

    # * @param  mixed  $field

    # * @param  mixed  $value

    # * @param  mixed  $rules

    # * @param  array  $messages

    # * @param  array  $attributes

    # * @return \Illuminate\Validation\Validator'
- name: validationMessages
  visibility: protected
  parameters: []
  comment: '# * Get the validation messages that should be used during prompt validation.

    # *

    # * @return array'
- name: validationAttributes
  visibility: protected
  parameters: []
  comment: '# * Get the validation attributes that should be used during prompt validation.

    # *

    # * @return array'
- name: restorePrompts
  visibility: protected
  parameters: []
  comment: '# * Restore the prompts output.

    # *

    # * @return void'
- name: selectFallback
  visibility: private
  parameters:
  - name: label
  - name: options
  - name: default
    default: 'null'
  comment: '# * Select fallback.

    # *

    # * @param  string  $label

    # * @param  array  $options

    # * @param  string|int|null  $default

    # * @return string|int'
- name: multiselectFallback
  visibility: private
  parameters:
  - name: label
  - name: options
  - name: default
    default: '[]'
  - name: required
    default: 'false'
  comment: '# * Multi-select fallback.

    # *

    # * @param  string  $label

    # * @param  array  $options

    # * @param  array  $default

    # * @param  bool|string  $required

    # * @return array'
traits:
- Illuminate\Console\PromptValidationException
- Laravel\Prompts\ConfirmPrompt
- Laravel\Prompts\MultiSearchPrompt
- Laravel\Prompts\MultiSelectPrompt
- Laravel\Prompts\PasswordPrompt
- Laravel\Prompts\Prompt
- Laravel\Prompts\SearchPrompt
- Laravel\Prompts\SelectPrompt
- Laravel\Prompts\SuggestPrompt
- Laravel\Prompts\TextareaPrompt
- Laravel\Prompts\TextPrompt
- stdClass
- Symfony\Component\Console\Input\InputInterface
interfaces: []
