name: platform_container_generator
version: 9.0.0
description: Protevus Platform Codegen support for using pkg:reflectable with pkg:platform_container.
homepage: https://protevus.com
documentation: https://docs.protevus.com
repository: https://git.protevus.com/protevus/platform/src/branch/main/packages/container/container_generator
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  platform_container: ^9.0.0
  reflectable: ^4.0.12
dev_dependencies:
  build_runner: ^2.4.13
  build_test: ^2.2.2
  test: ^1.25.8
  lints: ^4.0.0
# dependency_overrides:
#   platform_container:
#     path: ../platform_container
